# Final Project - Group 4
### Team member: Ting Huang, Lu Li, Jason Liu, Yu Luo, Yuwen Luo, Abenezer Tekle

### Statement:  We all attest that all participants equally contributed to this project.
__ __

# Part A: Candidate Table

## 1. Get data ##

In [1]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cn16.txt

--2020-12-05 18:11:38--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cn16.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.24.188
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.24.188|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 711038 (694K) [text/plain]
Saving to: ‘cn16.txt’

cn16.txt            100%[===================>] 694.37K  --.-KB/s    in 0.007s  

2020-12-05 18:11:38 (91.5 MB/s) - ‘cn16.txt’ saved [711038/711038]



In [2]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cn20.txt

--2020-12-05 18:11:52--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cn20.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.96.203
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.96.203|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 750144 (733K) [text/plain]
Saving to: ‘cn20.txt’

cn20.txt            100%[===================>] 732.56K  --.-KB/s    in 0.01s   

2020-12-05 18:11:52 (68.3 MB/s) - ‘cn20.txt’ saved [750144/750144]



In [3]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/ccl16.txt

--2020-12-05 18:14:32--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/ccl16.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.140.140
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.140.140|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 262686 (257K) [text/plain]
Saving to: ‘ccl16.txt’

ccl16.txt           100%[===================>] 256.53K  --.-KB/s    in 0.009s  

2020-12-05 18:14:32 (29.2 MB/s) - ‘ccl16.txt’ saved [262686/262686]



In [4]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/ccl20.txt

--2020-12-05 18:14:39--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/ccl20.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.217.47.116
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.217.47.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 288968 (282K) [text/plain]
Saving to: ‘ccl20.txt’

ccl20.txt           100%[===================>] 282.20K  --.-KB/s    in 0.004s  

2020-12-05 18:14:39 (63.1 MB/s) - ‘ccl20.txt’ saved [288968/288968]



In [56]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/weball20.txt

--2020-12-05 19:02:51--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/weball20.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.179.75
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.179.75|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 500344 (489K) [text/plain]
Saving to: ‘weball20.txt.1’

weball20.txt.1      100%[===================>] 488.62K  --.-KB/s    in 0.006s  

2020-12-05 19:02:51 (73.9 MB/s) - ‘weball20.txt.1’ saved [500344/500344]



In [57]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/weball16.txt

--2020-12-05 19:03:01--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/weball16.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.217.83.140
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.217.83.140|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 361997 (354K) [text/plain]
Saving to: ‘weball16.txt’

weball16.txt        100%[===================>] 353.51K  --.-KB/s    in 0.009s  

2020-12-05 19:03:01 (40.4 MB/s) - ‘weball16.txt’ saved [361997/361997]



## 2. Prepare Data

In [51]:
!csvstack -d "|" cn*.txt | csvcut -c 1,2,3,4,5 > candidate_master.csv

In [52]:
!csvstack -d "|" ccl*.txt | csvcut -c 1,4 > linkage.csv

In [20]:
!csvstack -d "|" weball*.txt | csvcut -c 1,7,18,28 > all_candidate.csv

## 3.Setup Data

In [2]:
%load_ext sql

In [3]:
!createdb -U student final_project_yu

createdb: error: could not connect to database template1: FATAL:  the database system is starting up


In [3]:
%sql postgresql://student@/final_project_yu

## 4. Import Data
__Candidate master Table__

In [49]:
%%sql
DROP TABLE IF EXISTS candidate_master cascade;

CREATE TABLE candidate_master (
    CAND_ID varchar(9) NOT NULL,
    CAND_NAME varchar(200),
    CAND_PTY_AFFILIATION varchar(3),
    CAND_ELECTION_YR numeric(4),
    CAND_OFFICE_ST varchar(2)
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [22]:
!pwd

/home/ubuntu


In [53]:
%%sql
COPY candidate_master FROM '/home/ubuntu/candidate_master.csv'
CSV;

 * postgresql://student@/final_project_yu
15164 rows affected.


[]

__Linkage table__

In [54]:
%%sql
DROP TABLE IF EXISTS linkage cascade;

CREATE TABLE linkage (
    CAND_ID varchar(9) NOT NULL,
    CMTE_ID varchar(9) NOT NULL
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [55]:
%%sql
COPY linkage FROM '/home/ubuntu/linkage.csv'
CSV;

 * postgresql://student@/final_project_yu
13454 rows affected.


[]

__All candidate table__

In [56]:
%%sql
DROP TABLE IF EXISTS all_candidate cascade;

CREATE TABLE all_candidate (
    CAND_ID varchar(9) NOT NULL,
    TRANS_FROM_AUTH numeric(14,2),
    TTL_INDIV_CONTRIB numeric(14,2),
    CVG_END_DT DATE
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [57]:
%%sql
COPY all_candidate FROM '/home/ubuntu/all_candidate.csv'
CSV;

 * postgresql://student@/final_project_yu
6855 rows affected.


[]

In [58]:
%%sql
select * from all_candidate limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('H4AK00123', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 1, 27)),
 ('H0AK00097', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 7, 18)),
 ('H6AK00045', Decimal('0.00'), Decimal('640393.04'), datetime.date(2016, 12, 31)),
 ('H8AK00116', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31)),
 ('H6AK00235', Decimal('0.00'), Decimal('999400.98'), datetime.date(2016, 12, 31))]

## 5. Dimension and fact design

__This is the dimension and fact table focus on candidate information:__

In [25]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/candidate_final.png")

### 5.1. Diagram 1 - candidate office

In [267]:
%%sql
DROP TABLE IF EXISTS OFFICE cascade;

CREATE TABLE OFFICE (
    OFFICE_KEY SERIAL PRIMARY KEY,
    CAND_OFFICE_STATE VARCHAR(2)
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [268]:
%%sql
INSERT INTO office (cand_office_state)
SELECT DISTINCT cand_office_st 
FROM candidate_master;

 * postgresql://student@/final_project_yu
57 rows affected.


[]

In [269]:
%%sql
select * from office
order by cand_office_state asc;

 * postgresql://student@/final_project_yu
57 rows affected.


[(45, 'AK'),
 (50, 'AL'),
 (13, 'AR'),
 (55, 'AS'),
 (56, 'AZ'),
 (26, 'CA'),
 (53, 'CO'),
 (14, 'CT'),
 (34, 'DC'),
 (25, 'DE'),
 (11, 'FL'),
 (41, 'GA'),
 (5, 'GU'),
 (7, 'HI'),
 (51, 'IA'),
 (40, 'ID'),
 (46, 'IL'),
 (8, 'IN'),
 (57, 'KS'),
 (31, 'KY'),
 (17, 'LA'),
 (49, 'MA'),
 (44, 'MD'),
 (12, 'ME'),
 (20, 'MI'),
 (42, 'MN'),
 (35, 'MO'),
 (21, 'MP'),
 (33, 'MS'),
 (18, 'MT'),
 (37, 'NC'),
 (2, 'ND'),
 (10, 'NE'),
 (27, 'NH'),
 (19, 'NJ'),
 (32, 'NM'),
 (3, 'NV'),
 (6, 'NY'),
 (4, 'OH'),
 (39, 'OK'),
 (28, 'OR'),
 (43, 'PA'),
 (30, 'PR'),
 (38, 'RI'),
 (23, 'SC'),
 (15, 'SD'),
 (47, 'TN'),
 (29, 'TX'),
 (1, 'US'),
 (22, 'UT'),
 (54, 'VA'),
 (24, 'VI'),
 (52, 'VT'),
 (48, 'WA'),
 (36, 'WI'),
 (9, 'WV'),
 (16, 'WY')]

### adding candidate state into all_candidate and then refer office dimension

In [59]:
%%sql
ALTER TABLE all_candidate
ADD COLUMN cand_office_state varchar(2),
ADD COLUMN office_key int,
ADD CONSTRAINT fk_office_key
    FOREIGN KEY (office_key)
    REFERENCES office (office_key);

 * postgresql://student@/final_project_yu
Done.


[]

In [60]:
%%sql
update all_candidate 
SET cand_office_state = candidate_master.cand_office_st
FROM candidate_master
WHERE all_candidate.CAND_ID = candidate_master.CAND_ID
;

 * postgresql://student@/final_project_yu
6835 rows affected.


[]

In [63]:
%%sql
update all_candidate 
SET  OFFICE_KEY= OFFICE.OFFICE_KEY
FROM OFFICE
WHERE OFFICE.cand_office_state = ALL_CANDIDATE.cand_office_state
;

 * postgresql://student@/final_project_yu
6835 rows affected.


[]

In [64]:
%%sql
SELECT * FROM ALL_CANDIDATE LIMIT 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('H0TX18235', Decimal('0.00'), Decimal('0.00'), datetime.date(2015, 10, 15), 'TX', 29),
 ('H0VA08040', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31), 'VA', 54),
 ('P20003711', Decimal('0.00'), Decimal('0.00'), datetime.date(2017, 1, 31), None, None),
 ('P60006244', Decimal('0.00'), Decimal('1260.00'), datetime.date(2016, 5, 9), None, None),
 ('P20003216', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31), None, None)]

### 5.2. Diagram 2 - Committee Linkage

### committee id add to all_candidate based on candidate_id

In [66]:
%%sql
ALTER TABLE all_candidate
ADD COLUMN CMTE_ID varchar(9);

 * postgresql://student@/final_project_yu
Done.


[]

In [67]:
%%sql
update all_candidate 
SET  CMTE_ID= LINKAGE.CMTE_ID
FROM LINKAGE
WHERE LINKAGE.CAND_ID = ALL_CANDIDATE.CAND_ID
;

 * postgresql://student@/final_project_yu
6788 rows affected.


[]

### Create committee_linkage where contains unique linkage to committee

In [68]:
%%sql
DROP TABLE IF EXISTS CMTE_LINK cascade;

CREATE TABLE CMTE_LINK (
    CMTE_LINK_KEY SERIAL PRIMARY KEY,
    CMTE_ID VARCHAR(9)
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [69]:
%%sql
INSERT INTO CMTE_LINK (CMTE_ID)
SELECT DISTINCT CMTE_ID 
FROM LINKAGE;

 * postgresql://student@/final_project_yu
11307 rows affected.


[]

In [34]:
%%sql
select * from cmte_link 
order by cmte_id desc
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[(967, 'C00763953'),
 (8003, 'C00763946'),
 (489, 'C00763912'),
 (11052, 'C00763904'),
 (4123, 'C00763896')]

### add committee_link_key to all_candidate

In [70]:
%%sql
ALTER TABLE all_candidate
ADD COLUMN cmte_link_key int,
ADD CONSTRAINT fk_cmte_link_key
    FOREIGN KEY (cmte_link_key)
    REFERENCES cmte_link (cmte_link_key);

 * postgresql://student@/final_project_yu
Done.


[]

In [71]:
%%sql
update all_candidate 
SET  cmte_link_KEY= cmte_link.cmte_link_KEY
FROM cmte_link
WHERE cmte_link.cmte_id = ALL_CANDIDATE.cmte_id
;

 * postgresql://student@/final_project_yu
6788 rows affected.


[]

### 5.3. Diagram 3 - Election

### create election table contain election_key, party affiliation and election year

In [73]:
%%sql
DROP TABLE IF EXISTS election cascade;

CREATE TABLE election (
    ELECTION_KEY SERIAL PRIMARY KEY,
    CAND_PTY_AFFILIATION varchar(3),
    CAND_ELECTION_YR numeric(4)
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [74]:
%%sql
INSERT INTO election (CAND_PTY_AFFILIATION, CAND_ELECTION_YR)
SELECT DISTINCT CAND_PTY_AFFILIATION, CAND_ELECTION_YR
FROM candidate_master;

 * postgresql://student@/final_project_yu
423 rows affected.


[]

### alter all_candidate fact table with election_key

In [75]:
%%sql
select * from all_candidate limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('H0TX18235', Decimal('0.00'), Decimal('0.00'), datetime.date(2015, 10, 15), 'TX', 29, 'C00557330', 6394),
 ('H0VA08040', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31), 'VA', 54, 'C00241349', 5327),
 ('P20003216', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31), None, None, 'C00500082', 9176),
 ('P20003711', Decimal('0.00'), Decimal('0.00'), datetime.date(2017, 1, 31), None, None, 'C00503763', 3613),
 ('P60006244', Decimal('0.00'), Decimal('1260.00'), datetime.date(2016, 5, 9), None, None, 'C00570192', 1376)]

In [76]:
%%sql
alter table all_candidate
add column year numeric(4);

 * postgresql://student@/final_project_yu
Done.


[]

In [77]:
%%sql
select * from all_candidate limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('H0TX18235', Decimal('0.00'), Decimal('0.00'), datetime.date(2015, 10, 15), 'TX', 29, 'C00557330', 6394, None),
 ('H0VA08040', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31), 'VA', 54, 'C00241349', 5327, None),
 ('P20003216', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31), None, None, 'C00500082', 9176, None),
 ('P20003711', Decimal('0.00'), Decimal('0.00'), datetime.date(2017, 1, 31), None, None, 'C00503763', 3613, None),
 ('P60006244', Decimal('0.00'), Decimal('1260.00'), datetime.date(2016, 5, 9), None, None, 'C00570192', 1376, None)]

In [78]:
%%sql
ALTER TABLE all_candidate
ADD COLUMN CAND_PTY_AFFILIATION varchar(3),
ADD COLUMN CAND_ELECTION_YR numeric(4),
ADD COLUMN election_key int,
ADD CONSTRAINT fk_election_key
    FOREIGN KEY (election_key)
    REFERENCES election (election_key);

 * postgresql://student@/final_project_yu
Done.


[]

In [79]:
%%sql
update all_candidate 
SET CAND_PTY_AFFILIATION = CANDIDATE_MASTER.CAND_PTY_AFFILIATION
FROM CANDIDATE_MASTER
WHERE CANDIDATE_MASTER.CAND_ID = ALL_CANDIDATE.CAND_ID
;

 * postgresql://student@/final_project_yu
6835 rows affected.


[]

In [80]:
%%sql
select count(*),YEAR from ALL_CANDIDATE
group by YEAR
order by YEAR DESC;

 * postgresql://student@/final_project_yu
1 rows affected.


[(6855, None)]

In [81]:
%%sql
select count(*),CAND_ELECTION_YR from election
group by CAND_ELECTION_YR
order by CAND_ELECTION_YR DESC;

 * postgresql://student@/final_project_yu
45 rows affected.


[(1, Decimal('2916')),
 (1, Decimal('2820')),
 (2, Decimal('2106')),
 (1, Decimal('2069')),
 (1, Decimal('2064')),
 (1, Decimal('2052')),
 (2, Decimal('2048')),
 (3, Decimal('2044')),
 (4, Decimal('2040')),
 (7, Decimal('2036')),
 (4, Decimal('2032')),
 (1, Decimal('2029')),
 (5, Decimal('2028')),
 (2, Decimal('2026')),
 (3, Decimal('2025')),
 (16, Decimal('2024')),
 (12, Decimal('2022')),
 (8, Decimal('2021')),
 (80, Decimal('2020')),
 (14, Decimal('2019')),
 (28, Decimal('2018')),
 (5, Decimal('2017')),
 (104, Decimal('2016')),
 (14, Decimal('2015')),
 (15, Decimal('2014')),
 (5, Decimal('2013')),
 (16, Decimal('2012')),
 (3, Decimal('2011')),
 (18, Decimal('2010')),
 (4, Decimal('2009')),
 (11, Decimal('2008')),
 (3, Decimal('2007')),
 (6, Decimal('2006')),
 (4, Decimal('2004')),
 (2, Decimal('2002')),
 (1, Decimal('2001')),
 (3, Decimal('2000')),
 (2, Decimal('1998')),
 (3, Decimal('1996')),
 (1, Decimal('1994')),
 (2, Decimal('1992')),
 (1, Decimal('1990')),
 (1, Decimal('1988')),
 (1, Decimal('1986')),
 (2, Decimal('1984'))]

In [82]:
%%sql
update all_candidate 
SET CAND_ELECTION_YR = CANDIDATE_MASTER.CAND_ELECTION_YR
FROM CANDIDATE_MASTER
WHERE CANDIDATE_MASTER.CAND_ID = ALL_CANDIDATE.CAND_ID
;

 * postgresql://student@/final_project_yu
6835 rows affected.


[]

In [83]:
%%sql
update all_candidate 
SET ELECTION_KEY = ELECTION.ELECTION_KEY
FROM ELECTION
WHERE ELECTION.CAND_ELECTION_YR = ALL_CANDIDATE.CAND_ELECTION_YR AND ELECTION.CAND_PTY_AFFILIATION = ALL_CANDIDATE.CAND_PTY_AFFILIATION
;

 * postgresql://student@/final_project_yu
6834 rows affected.


[]

In [84]:
%%sql
select distinct * from all_candidate limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('S0NY00667', Decimal('0.00'), Decimal('0.00'), datetime.date(2020, 9, 30), 'NY', 6, 'C00749226', 1029, None, 'DEM', Decimal('2020'), 139),
 ('H2OH03141', Decimal('0.00'), Decimal('0.00'), datetime.date(2020, 9, 30), 'OH', 4, 'C00517441', 6179, None, 'REP', Decimal('2012'), 356),
 ('H0WY01028', Decimal('0.00'), Decimal('8591.85'), datetime.date(2020, 10, 14), 'WY', 16, 'C00740647', 8625, None, 'DEM', Decimal('2020'), 139),
 ('S4AK00214', Decimal('190.00'), Decimal('177320.00'), datetime.date(2016, 12, 31), 'AK', 45, 'C00568477', 9188, None, 'REP', Decimal('2020'), 55),
 ('H6NE03115', Decimal('0.00'), Decimal('329161.30'), datetime.date(2020, 10, 14), 'NE', 10, 'C00412890', 3529, None, 'REP', Decimal('2016'), 59)]

### 5.4. Diagram 4 - Candidate_info

In [290]:
%%sql
DROP TABLE IF EXISTS candidate_info cascade;

CREATE TABLE candidate_info (
    info_KEY SERIAL PRIMARY KEY,
    CAND_ID varchar(9),
    CAND_NAME VARCHAR(200)
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [291]:
%%sql
INSERT INTO CANDIDATE_INFO (CAND_ID, CAND_NAME)
SELECT DISTINCT CAND_ID, CAND_NAME
FROM candidate_master;

 * postgresql://student@/final_project_yu
13555 rows affected.


[]

### alter all candidate fact table to insert info_key

In [86]:
%%sql
ALTER TABLE all_candidate
ADD COLUMN info_key int,
ADD CONSTRAINT fk_info_key
    FOREIGN KEY (info_key)
    REFERENCES candidate_info (info_key);

 * postgresql://student@/final_project_yu
Done.


[]

In [87]:
%%sql
update all_candidate 
SET info_key = candidate_info.info_key
FROM candidate_info
WHERE candidate_info.cand_id = all_candidate.cand_id;

 * postgresql://student@/final_project_yu
6835 rows affected.


[]

In [88]:
%%sql
select * from all_candidate
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('H0CA10149', Decimal('0.00'), Decimal('413839.18'), datetime.date(2020, 10, 14), 'CA', 26, 'C00462697', 5015, None, 'DEM', Decimal('2016'), 86, 7727),
 ('P20003216', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 12, 31), None, None, 'C00500082', 9176, None, None, None, None, None),
 ('P20003711', Decimal('0.00'), Decimal('0.00'), datetime.date(2017, 1, 31), None, None, 'C00503763', 3613, None, None, None, None, None),
 ('P60006244', Decimal('0.00'), Decimal('1260.00'), datetime.date(2016, 5, 9), None, None, 'C00570192', 1376, None, None, None, None, None),
 ('P60005998', Decimal('0.00'), Decimal('0.00'), datetime.date(2016, 9, 30), None, None, 'C00570929', 2581, None, None, None, None, None)]

### 5.5 Diagram 5 - Coverage year

In [89]:
%%sql
update all_candidate
set year = extract(year from cvg_end_dt);

 * postgresql://student@/final_project_yu
6855 rows affected.


[]

In [91]:
%%sql
DROP TABLE IF EXISTS COVERAGE_YEAR cascade;

CREATE TABLE COVERAGE_YEAR (
    COVERAGE_YEAR_KEY SERIAL PRIMARY KEY,
    YEAR INT
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [92]:
%%sql
INSERT INTO COVERAGE_YEAR(YEAR)
SELECT DISTINCT YEAR FROM ALL_CANDIDATE;

 * postgresql://student@/final_project_yu
5 rows affected.


[]

In [94]:
%%sql
alter table all_candidate
add column coverage_year_key int,
add CONSTRAINT fk_coverage_year_key
    FOREIGN KEY (coverage_year_key)
    REFERENCES coverage_year (coverage_year_key);

 * postgresql://student@/final_project_yu
Done.


[]

In [95]:
%%sql
update all_candidate 
SET coverage_year_key = coverage_year.coverage_year_key
FROM coverage_year
WHERE coverage_year.year = all_candidate.year;

 * postgresql://student@/final_project_yu
6855 rows affected.


[]

In [96]:
%%sql
select * from all_candidate limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('S4KS00127', Decimal('0.00'), Decimal('92302.00'), datetime.date(2015, 12, 31), 'KS', 57, 'C00550020', 11058, Decimal('2015'), 'REP', Decimal('2014'), 1, 882, 1),
 ('P60007903', Decimal('0.00'), Decimal('0.00'), datetime.date(2015, 6, 30), 'US', 1, 'C00579284', 4728, Decimal('2015'), 'REP', Decimal('2016'), 59, 11255, 1),
 ('H6OH16029', Decimal('0.00'), Decimal('0.00'), datetime.date(2015, 6, 30), 'OH', 4, 'C00005041', 2611, Decimal('2015'), 'REP', Decimal('2008'), 32, 12610, 1),
 ('S4NM00092', Decimal('0.00'), Decimal('0.00'), datetime.date(2015, 6, 30), 'NM', 32, 'C00553248', 5198, Decimal('2015'), 'REP', Decimal('2014'), 1, 12800, 1),
 ('H6ID02175', Decimal('0.00'), Decimal('0.00'), datetime.date(2015, 12, 26), 'ID', 40, 'C00592477', 5374, Decimal('2015'), 'REP', Decimal('2016'), 59, 11225, 1)]

In [9]:
%%sql
select coverage_year_key,count(*) from all_candidate
group by coverage_year_key
order by coverage_year_key;

 * postgresql://student@/final_project_yu
5 rows affected.


[(1, 440), (2, 9), (3, 764), (4, 3185), (5, 2457)]

In [8]:
%%sql
select * from coverage_year;

 * postgresql://student@/final_project_yu
5 rows affected.


[(1, 2015), (2, 2017), (3, 2019), (4, 2020), (5, 2016)]

### 6. Clean fact table - 'all candidate'

### delete extra columns in fact table

In [98]:
%%sql
alter table all_candidate
drop column cand_id,
drop column cand_office_state,
drop column cmte_id,
drop column cand_pty_affiliation,
drop column cand_election_yr,
drop column year;

 * postgresql://student@/final_project_yu
Done.


[]

In [100]:
%%sql
alter table all_candidate
drop column cvg_end_dt;

 * postgresql://student@/final_project_yu
Done.


[]

In [101]:
%%sql
select * from all_candidate limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('0.00'), Decimal('92302.00'), 57, 11058, 1, 882, 1),
 (Decimal('0.00'), Decimal('0.00'), 1, 4728, 59, 11255, 1),
 (Decimal('0.00'), Decimal('0.00'), 4, 2611, 32, 12610, 1),
 (Decimal('0.00'), Decimal('0.00'), 32, 5198, 1, 12800, 1),
 (Decimal('0.00'), Decimal('0.00'), 40, 5374, 59, 11225, 1)]

__Check for duplicates, we could see the combination of all facts is distinct.__

In [5]:
%%sql
select *, count(*) as count from all_candidate
group by trans_from_auth,ttl_indiv_contrib, office_key,cmte_link_key,election_key,info_key,coverage_year_key
having count(*) > 1;

 * postgresql://student@/final_project_yu
0 rows affected.


[]

__ __

# Part B: Contribution Table

## 1. Get Data

In [4]:
## contribution by individual
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itcont16.zip

--2020-12-06 16:21:14--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itcont16.zip
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.217.36.52
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.217.36.52|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503806120 (480M) [application/zip]
Saving to: ‘itcont16.zip’

itcont16.zip        100%[===================>] 480.47M  62.8MB/s    in 6.8s    

2020-12-06 16:21:21 (71.0 MB/s) - ‘itcont16.zip’ saved [503806120/503806120]



In [5]:
!unzip -o itcont16.zip

Archive:  itcont16.zip
  inflating: itcont_2016_20151030_20160121.txt  
  inflating: __MACOSX/._itcont_2016_20151030_20160121.txt  
  inflating: itcont_2016_20160122_20160405.txt  
  inflating: __MACOSX/._itcont_2016_20160122_20160405.txt  
  inflating: itcont_2016_20160405_20160523.txt  
  inflating: __MACOSX/._itcont_2016_20160405_20160523.txt  
  inflating: itcont_2016_20160523_20160716.txt  
  inflating: __MACOSX/._itcont_2016_20160523_20160716.txt  
  inflating: itcont_2016_20160717_20160830.txt  
  inflating: __MACOSX/._itcont_2016_20160717_20160830.txt  
  inflating: itcont_2016_20160831_20161003.txt  
  inflating: __MACOSX/._itcont_2016_20160831_20161003.txt  
  inflating: itcont_2016_20161004_20161028.txt  
  inflating: __MACOSX/._itcont_2016_20161004_20161028.txt  


In [6]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itcont20.zip

--2020-12-06 16:26:32--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itcont20.zip
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.25.204
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.25.204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1678917161 (1.6G) [application/zip]
Saving to: ‘itcont20.zip’

itcont20.zip        100%[===================>]   1.56G  63.5MB/s    in 23s     

2020-12-06 16:26:55 (70.2 MB/s) - ‘itcont20.zip’ saved [1678917161/1678917161]



In [7]:
!unzip -o itcont20.zip

Archive:  itcont20.zip
  inflating: itcont_2020_20201008_20201012.txt  
  inflating: __MACOSX/._itcont_2020_20201008_20201012.txt  
  inflating: itcont_2020_20191230_20200130.txt  
  inflating: __MACOSX/._itcont_2020_20191230_20200130.txt  
  inflating: itcont_2020_20200131_20200219.txt  
  inflating: __MACOSX/._itcont_2020_20200131_20200219.txt  
  inflating: itcont_2020_20200220_20200305.txt  
  inflating: __MACOSX/._itcont_2020_20200220_20200305.txt  
  inflating: itcont_2020_20200306_20200330.txt  
  inflating: __MACOSX/._itcont_2020_20200306_20200330.txt  
  inflating: itcont_2020_20200331_20200426.txt  
  inflating: __MACOSX/._itcont_2020_20200331_20200426.txt  
  inflating: itcont_2020_20200427_20200516.txt  
  inflating: __MACOSX/._itcont_2020_20200427_20200516.txt  
  inflating: itcont_2020_20200517_20200603.txt  
  inflating: __MACOSX/._itcont_2020_20200517_20200603.txt  
  inflating: itcont_2020_20200603_20200617.txt  
  inflating: __MACOSX/._itcont_2020_20200603_20200617.tx

In [8]:
## contribution from one committee to another
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itoth16.txt

--2020-12-06 16:28:32--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itoth16.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.186.75
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.186.75|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 396109693 (378M) [text/plain]
Saving to: ‘itoth16.txt’

itoth16.txt         100%[===================>] 377.76M  67.8MB/s    in 6.4s    

2020-12-06 16:28:39 (58.6 MB/s) - ‘itoth16.txt’ saved [396109693/396109693]



In [9]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itoth20.txt

--2020-12-06 16:28:48--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itoth20.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.217.70.92
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.217.70.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 703166088 (671M) [text/plain]
Saving to: ‘itoth20.txt’

itoth20.txt         100%[===================>] 670.59M  77.3MB/s    in 9.1s    

2020-12-06 16:28:57 (73.8 MB/s) - ‘itoth20.txt’ saved [703166088/703166088]



In [10]:
## contribution from committee to another candidate
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itpas16.txt

--2020-12-06 16:29:10--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itpas16.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.217.39.172
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.217.39.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 86838966 (83M) [text/plain]
Saving to: ‘itpas16.txt’

itpas16.txt         100%[===================>]  82.82M  78.8MB/s    in 1.1s    

2020-12-06 16:29:11 (78.8 MB/s) - ‘itpas16.txt’ saved [86838966/86838966]



In [11]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itpas20.txt

--2020-12-06 16:29:18--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/itpas20.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.25.76
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.25.76|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 76612384 (73M) [text/plain]
Saving to: ‘itpas20.txt’

itpas20.txt         100%[===================>]  73.06M  68.7MB/s    in 1.1s    

2020-12-06 16:29:19 (68.7 MB/s) - ‘itpas20.txt’ saved [76612384/76612384]



In [12]:
## committee master
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cm16.txt

--2020-12-06 16:30:04--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cm16.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.113.83
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.113.83|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2153013 (2.1M) [text/plain]
Saving to: ‘cm16.txt’

cm16.txt            100%[===================>]   2.05M  --.-KB/s    in 0.03s   

2020-12-06 16:30:04 (76.1 MB/s) - ‘cm16.txt’ saved [2153013/2153013]



In [13]:
!wget https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cm20.txt

--2020-12-06 16:30:15--  https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/cm20.txt
Resolving dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)... 52.216.143.148
Connecting to dmfa-2020-lu.s3.amazonaws.com (dmfa-2020-lu.s3.amazonaws.com)|52.216.143.148|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2189120 (2.1M) [text/plain]
Saving to: ‘cm20.txt’

cm20.txt            100%[===================>]   2.09M  --.-KB/s    in 0.03s   

2020-12-06 16:30:15 (75.0 MB/s) - ‘cm20.txt’ saved [2189120/2189120]



## 2. Prepare for needed data

In [18]:
!csvstack -d "|" cm*.txt | csvcut -c 1,2,11 > committee_master.csv

In [27]:
!csvstack -d "|" itcont_20*_20*_20*.txt | csvcut -c 1,8,10,13,14,15,16,21 > individuals_to_committees_contribution.csv

In [28]:
!csvstack -d "|" itpas*.txt | csvcut -c 1,8,10,13,14,15,16,22 > committees_to_candidates_contribution.csv

In [29]:
!csvstack -d "|" itoth*.txt | csvcut -c 1,8,10,13,14,15,16,21 > committees_to_committees_contribution.csv

## 3. create table to import data

__Committee master__

In [11]:
%%sql
DROP TABLE IF EXISTS committee_master cascade;

CREATE TABLE committee_master (
    CMTE_ID VARCHAR(9),
    CMTE_NM varchar(200),
    CMTE_PTY_AFFILIATION VARCHAR(3)
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [12]:
%%sql
COPY committee_master FROM '/home/ubuntu/committee_master.csv'
CSV;

 * postgresql://student@/final_project_yu
35755 rows affected.


[]

__individuals_to_committees_contribution AND add contribution type__

In [30]:
%%sql
DROP TABLE IF EXISTS individuals_to_committees_contribution cascade;

CREATE TABLE individuals_to_committees_contribution (
    CMTE_ID VARCHAR(9),
    NAME varchar(200),
    STATE VARCHAR(2),
    OCCUPATION VARCHAR(38),
    TRANSACTION_DT numeric(8),
    TRANSACTION_AMT numeric(14,2),
    OTHER_ID VARCHAR(9),
    SUB_ID NUMERIC(19) NOT NULL
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [31]:
%%sql
COPY individuals_to_committees_contribution FROM '/home/ubuntu/individuals_to_committees_contribution.csv'
CSV;

 * postgresql://student@/final_project_yu
53765647 rows affected.


[]

add contribution type as 'IND_COM'

In [32]:
%%sql
alter table individuals_to_committees_contribution
add column contribution_type varchar(7);

 * postgresql://student@/final_project_yu
Done.


[]

In [33]:
%%sql
update individuals_to_committees_contribution
set contribution_type = 'IND_COM';

 * postgresql://student@/final_project_yu
53765647 rows affected.


[]

__committees_to_candidates_contribution__

In [34]:
%%sql
DROP TABLE IF EXISTS committees_to_candidates_contribution cascade;

CREATE TABLE committees_to_candidates_contribution (
    CMTE_ID VARCHAR(9),
    NAME varchar(200),
    STATE VARCHAR(2),
    OCCUPATION VARCHAR(38),
    TRANSACTION_DT numeric(8),
    TRANSACTION_AMT numeric(14,2),
    OTHER_ID VARCHAR(9),
    SUB_ID NUMERIC(19) NOT NULL
)

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [35]:
%%sql
COPY committees_to_candidates_contribution FROM '/home/ubuntu/committees_to_candidates_contribution.csv'
CSV;

 * postgresql://student@/final_project_yu
950152 rows affected.


[]

In [36]:
%%sql
alter table committees_to_candidates_contribution
add column contribution_type varchar(7);

 * postgresql://student@/final_project_yu
Done.


[]

In [37]:
%%sql
update committees_to_candidates_contribution
set contribution_type = 'COM_CAN';

 * postgresql://student@/final_project_yu
950152 rows affected.


[]

__committees_to_committees_contribution__

In [38]:
%%sql
DROP TABLE IF EXISTS committees_to_committees_contribution cascade;

CREATE TABLE committees_to_committees_contribution (
    CMTE_ID VARCHAR(9),
    NAME varchar(200),
    STATE VARCHAR(2),
    OCCUPATION VARCHAR(38),
    TRANSACTION_DT numeric(8),
    TRANSACTION_AMT numeric(14,2),
    OTHER_ID VARCHAR(9),
    SUB_ID NUMERIC(19) NOT NULL
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [39]:
%%sql
COPY committees_to_committees_contribution FROM '/home/ubuntu/committees_to_committees_contribution.csv'
CSV;

 * postgresql://student@/final_project_yu
5829302 rows affected.


[]

In [40]:
%%sql
alter table committees_to_committees_contribution
add column contribution_type varchar(7);

 * postgresql://student@/final_project_yu
Done.


[]

In [41]:
%%sql
update committees_to_committees_contribution
set contribution_type = 'COM_COM';

 * postgresql://student@/final_project_yu
5829302 rows affected.


[]

In [16]:
%%sql
select * from committees_to_committees_contribution
where other_id is not null
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('C00390831', None, None, None, Decimal('11182016'), Decimal('-5000.00'), 'C00465963', Decimal('1012620170033182297'), 'COM_COM'),
 ('C00461046', None, 'OK', None, Decimal('11032016'), Decimal('5000.00'), 'C00330233', Decimal('2011220171367497743'), 'COM_COM'),
 ('C00562587', 'GOOGLE', 'CA', None, None, Decimal('452.00'), 'S6MO00362', Decimal('4010520171359541656'), 'COM_COM'),
 ('C00564807', None, None, None, Decimal('10032016'), Decimal('2500.00'), 'C00620518', Decimal('1030620170033785448'), 'COM_COM'),
 ('C70004627', None, None, None, None, Decimal('0.00'), 'H2NV00050', Decimal('2071920161306852663'), 'COM_COM')]

In [5]:
%%sql
select count(*) from committees_to_committees_contribution
where other_id is null;

 * postgresql://student@/final_project_yu
1 rows affected.


[(4328152,)]

In [6]:
%%sql
select count(*) from committees_to_candidates_contribution
where other_id is null;

 * postgresql://student@/final_project_yu
1 rows affected.


[(0,)]

In [7]:
%%sql
select * from committees_to_candidates_contribution
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('C00581306', None, None, None, Decimal('12132015'), Decimal('814.00'), 'C00577130', Decimal('2011220161260556123'), 'COM_CAN'),
 ('C70001318', None, None, None, Decimal('11082016'), Decimal('965.00'), 'H0CA15148', Decimal('4020820171369944905'), 'COM_CAN'),
 ('C00499020', 'GOOGLE', 'CA', None, None, Decimal('250.00'), 'S6CO00226', Decimal('4080320161307866021'), 'COM_CAN'),
 ('C70000120', None, None, None, Decimal('1302016'), Decimal('118.00'), 'P00003392', Decimal('2051620161292819070'), 'COM_CAN'),
 ('C00661462', 'PAYPAL', 'CA', None, None, Decimal('201.00'), 'H2NY22071', Decimal('4102320201883197769'), 'COM_CAN')]

In [8]:
%%sql
select count(*) from individuals_to_committees_contribution
where other_id is null;

 * postgresql://student@/final_project_yu
1 rows affected.


[(16409192,)]

__CREATE CONTRIBUTION_FACT TABLE TO MERGE ALL THREE CONTRIBUTION TABLE__

In [9]:
%%sql
DROP TABLE IF EXISTS CONTRIBUTION_FACT_REF cascade;

CREATE TABLE CONTRIBUTION_FACT_REF (
    CMTE_ID VARCHAR(9),
    NAME varchar(200),
    STATE VARCHAR(2),
    OCCUPATION VARCHAR(38),
    TRANSACTION_DT numeric(8),
    TRANSACTION_AMT numeric(14,2),
    OTHER_ID VARCHAR(9),
    SUB_ID NUMERIC(19) NOT NULL
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [10]:
%%sql
alter table contribution_fact_ref
add column contribution_type varchar(7);

 * postgresql://student@/final_project_yu
Done.


[]

In [11]:
%%sql
INSERT INTO CONTRIBUTION_FACT_REF (CMTE_ID, NAME, STATE, OCCUPATION, TRANSACTION_DT, TRANSACTION_AMT, OTHER_ID, SUB_ID, contribution_type)

SELECT *
FROM committees_to_committees_contribution;

 * postgresql://student@/final_project_yu
5829302 rows affected.


[]

In [12]:
%%sql
INSERT INTO CONTRIBUTION_FACT_REF (CMTE_ID, NAME, STATE, OCCUPATION, TRANSACTION_DT, TRANSACTION_AMT, OTHER_ID, SUB_ID, contribution_type)

SELECT *
FROM committees_to_candidates_contribution;

 * postgresql://student@/final_project_yu
950152 rows affected.


[]

In [13]:
%%sql
INSERT INTO CONTRIBUTION_FACT_REF (CMTE_ID, NAME, STATE, OCCUPATION, TRANSACTION_DT, TRANSACTION_AMT, OTHER_ID, SUB_ID, contribution_type)

SELECT *
FROM individuals_to_committees_contribution;

 * postgresql://student@/final_project_yu
53765647 rows affected.


[]

In [45]:
%%sql
select count(*) from CONTRIBUTION_FACT_REF;

 * postgresql://student@/final_project_yu
1 rows affected.


[(60545101,)]

## 4. Create dimension

__We would like to split our data into 1 fact table and 6 dimension tables:__

In [41]:
from IPython.display import Image
Image(url = 'https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/CONTRIBUTION_FINAL.jpeg')

### 4.1 Dimension 1 - Type_v2

__We here want to create a dimension to differentiate contribution type:__
+ COM_CAN - Contribution from committee to candidate
+ IND_COM - Contribution from individual to committee
+ COM_COM - Contribution from committee to committee

In [14]:
%%sql
DROP TABLE IF EXISTS TYPE_v2 cascade;

CREATE TABLE TYPE_v2 (
    TYPE_KEY SERIAL PRIMARY KEY,
    CONTRIBUTION_TYPE VARCHAR(7)
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [15]:
%%sql
insert into TYPE_v2 (CONTRIBUTION_TYPE)
SELECT DISTINCT CONTRIBUTION_TYPE FROM CONTRIBUTION_FACT_REF;

 * postgresql://student@/final_project_yu
3 rows affected.


[]

In [16]:
%%sql
alter table contribution_fact_ref
add column type_key int;

 * postgresql://student@/final_project_yu
Done.


[]

In [19]:
%%sql
ALTER TABLE contribution_fact_ref
ADD CONSTRAINT fk_type_v2
    FOREIGN KEY (type_key)
    REFERENCES TYPE_V2 (TYPE_KEY);

 * postgresql://student@/final_project_yu
Done.


[]

In [21]:
%%sql
update contribution_fact_ref
set type_key = TYPE_V2.type_key
FROM TYPE_V2
WHERE TYPE_V2.contribution_type = contribution_fact_ref.contribution_type;

 * postgresql://student@/final_project_yu
60545101 rows affected.


[]

In [22]:
%%sql
select * from TYPE_V2;

 * postgresql://student@/final_project_yu
3 rows affected.


[(1, 'COM_CAN'), (2, 'IND_COM'), (3, 'COM_COM')]

### 4.2 Dimension 2 - DATE_V2

__Day dimension will include the year, month and date of the contribution__

In [23]:
%%sql
DROP TABLE IF EXISTS DATE_V2 cascade;

CREATE TABLE DATE_V2 (
    DATE_KEY SERIAL PRIMARY KEY,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [24]:
%%sql
INSERT INTO DATE_V2 (YEAR,MONTH,DAY)
SELECT DISTINCT cast(right(cast(TRANSACTION_DT as varchar(8)),4) as INTEGER) as YEAR,
        cast(left(cast(TRANSACTION_DT as varchar(8)),length(cast(TRANSACTION_DT as varchar(8)))-6) as INTEGER) as MONTH, 
       cast(left(right(cast(TRANSACTION_DT as varchar(8)),6),2) as INTEGER) as DAY
FROM CONTRIBUTION_FACT_REF;

 * postgresql://student@/final_project_yu
2303 rows affected.


[]

In [25]:
%%sql
alter table contribution_fact_ref
add column date_key integer,
add constraint fk_date_v2
    FOREIGN KEY (date_key)
    REFERENCES date_v2 (date_key);

 * postgresql://student@/final_project_yu
Done.


[]

In [34]:
%%sql
UPDATE contribution_fact_ref
SET date_key = date_v2.date_key
FROM date_v2
WHERE cast(right(cast(contribution_fact_ref.TRANSACTION_DT as varchar(8)),4) as INTEGER)= date_v2.year 
and cast(left(cast(contribution_fact_ref.TRANSACTION_DT as varchar(8)),length(cast(TRANSACTION_DT as varchar(8)))-6) as INTEGER) = date_v2.month
and cast(left(right(cast(contribution_fact_ref.TRANSACTION_DT as varchar(8)),6),2) as INTEGER) = date_v2.day;

 * postgresql://student@/final_project_yu
60537947 rows affected.


[]

In [35]:
%%sql
select distinct month from date_v2
where year = 2020
order by month;

 * postgresql://student@/final_project_yu
12 rows affected.


[(1,), (2,), (3,), (4,), (5,), (6,), (7,), (8,), (9,), (10,), (11,), (12,)]

In [36]:
%%sql
select day,count(*) from date_v2
group by day
order by day;

 * postgresql://student@/final_project_yu
32 rows affected.


[(1, 69),
 (2, 69),
 (3, 70),
 (4, 77),
 (5, 72),
 (6, 73),
 (7, 75),
 (8, 73),
 (9, 75),
 (10, 79),
 (11, 75),
 (12, 72),
 (13, 73),
 (14, 77),
 (15, 72),
 (16, 79),
 (17, 77),
 (18, 78),
 (19, 78),
 (20, 77),
 (21, 81),
 (22, 77),
 (23, 74),
 (24, 77),
 (25, 78),
 (26, 72),
 (27, 79),
 (28, 75),
 (29, 76),
 (30, 76),
 (31, 47),
 (None, 1)]

__From the result, we could see that no day or month is outside the range of what months and days should be for common sense.__

In [37]:
%%sql
select * from contribution_fact_ref
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('C00703975', 'ORTEL, WADE', 'RI', None, Decimal('9142020'), Decimal('300.00'), None, Decimal('4102320201883514849'), 'IND_COM', 2, 1831),
 ('C00580100', 'BREWER, LARRY', 'IL', 'RETIRED', Decimal('9092020'), Decimal('250.00'), 'C00694323', Decimal('4102420201885631414'), 'IND_COM', 2, 1675),
 ('C00703975', 'REUTER, MARK W', 'NJ', None, Decimal('9142020'), Decimal('50.00'), None, Decimal('4102320201883518592'), 'IND_COM', 2, 1831),
 ('C00580100', 'BREIDUNG, JAMES', 'FL', 'RETIRED', Decimal('9112020'), Decimal('42.00'), None, Decimal('4102420201885630765'), 'IND_COM', 2, 213),
 ('C00703975', 'PARASKEVAS, NANCY', 'NM', None, Decimal('9142020'), Decimal('50.00'), None, Decimal('4102320201883515349'), 'IND_COM', 2, 1831)]

### 4.3 Dimension 3 - Beneficiary_v2

__Beneficiary table will contain the id, name and party affiliation of the beneficiary__

In [39]:
%%sql
DROP TABLE IF EXISTS BENEFICIARY_V2 cascade;

CREATE TABLE BENEFICIARY_V2 (
    BENEFICIARY_KEY SERIAL PRIMARY KEY,
    CMTE_ID varchar(9),
    CMTE_NAME VARCHAR(200),
    CMTE_PTY_AFFILIATION VARCHAR(3)
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [40]:
%%sql
insert into beneficiary_v2 (CMTE_ID, CMTE_NAME,CMTE_PTY_AFFILIATION)
SELECT DISTINCT CMTE_ID as CMTE_ID, CMTE_NM as CMTE_NAME, CMTE_PTY_AFFILIATION as CMTE_PTY_AFFILIATION
from committee_master;

 * postgresql://student@/final_project_yu
29583 rows affected.


[]

In [42]:
%%sql
alter table contribution_fact_ref
add column BENEFICIARY_KEY integer,
add constraint fk_beneficiary_v2
    foreign key (BENEFICIARY_KEY)
    references BENEFICIARY_V2 (BENEFICIARY_KEY);

 * postgresql://student@/final_project_yu
Done.


[]

In [43]:
%%sql
update contribution_fact_ref
set BENEFICIARY_KEY = BENEFICIARY_V2.BENEFICIARY_KEY
FROM BENEFICIARY_V2
WHERE contribution_fact_ref.CMTE_ID = BENEFICIARY_V2.CMTE_ID;

 * postgresql://student@/final_project_yu
60545076 rows affected.


[]

In [44]:
%%sql
select * from contribution_fact_ref
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('C00703975', 'REUTER, MARK W', 'NJ', None, Decimal('9142020'), Decimal('50.00'), None, Decimal('4102320201883518592'), 'IND_COM', 2, 1831, 21666),
 ('C00580100', 'BREIDUNG, JAMES', 'FL', 'RETIRED', Decimal('9112020'), Decimal('42.00'), None, Decimal('4102420201885630765'), 'IND_COM', 2, 213, 10982),
 ('C00703975', 'PARASKEVAS, NANCY', 'NM', None, Decimal('9142020'), Decimal('50.00'), None, Decimal('4102320201883515349'), 'IND_COM', 2, 1831, 21666),
 ('C00703975', 'WIENER, DAN', 'NY', 'PHYSICIAN', Decimal('9142020'), Decimal('250.00'), 'C00401224', Decimal('4102320201883530245'), 'IND_COM', 2, 1831, 21666),
 ('C00703975', 'MULLER, AL', 'CA', 'CTO', Decimal('9142020'), Decimal('100.00'), 'C00401224', Decimal('4102320201883512878'), 'IND_COM', 2, 1831, 21666)]

### 4.4 Dimension 4 - Contributor Location

__Region and State of the contributir will be included in this contributor location table__

In [46]:
%%sql
DROP TABLE IF EXISTS CONTRIBUTOR_LOCATION cascade;

CREATE TABLE CONTRIBUTOR_LOCATION (
    CONTRIBUTOR_LOCATION_KEY SERIAL PRIMARY KEY,
    STATE VARCHAR(2),
    REGION VARCHAR(20)
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [47]:
%%sql
insert into CONTRIBUTOR_LOCATION (STATE)
SELECT DISTINCT STATE as STATE
from CONTRIBUTION_FACT_REF;

 * postgresql://student@/final_project_yu
125 rows affected.


[]

In [48]:
%%sql
select * from contributor_location;

 * postgresql://student@/final_project_yu
125 rows affected.


[(1, 'KS', None),
 (2, '75', None),
 (3, 'EN', None),
 (4, 'FC', None),
 (5, None, None),
 (6, 'BS', None),
 (7, 'NV', None),
 (8, 'OH', None),
 (9, 'MH', None),
 (10, 'NY', None),
 (11, 'AU', None),
 (12, 'NS', None),
 (13, 'QC', None),
 (14, 'BC', None),
 (15, 'AT', None),
 (16, 'GE', None),
 (17, 'WV', None),
 (18, 'NF', None),
 (19, 'AR', None),
 (20, 'HO', None),
 (21, 'CT', None),
 (22, 'KA', None),
 (23, 'BR', None),
 (24, 'YT', None),
 (25, 'WY', None),
 (26, 'LA', None),
 (27, 'MT', None),
 (28, 'MI', None),
 (29, 'XX', None),
 (30, 'FF', None),
 (31, 'SA', None),
 (32, 'DE', None),
 (33, 'AA', None),
 (34, 'SK', None),
 (35, 'SJ', None),
 (36, 'NH', None),
 (37, 'AB', None),
 (38, 'OR', None),
 (39, 'SH', None),
 (40, 'UK', None),
 (41, 'DC', None),
 (42, 'WI', None),
 (43, 'DF', None),
 (44, 'RI', None),
 (45, 'LE', None),
 (46, 'AP', None),
 (47, 'VD', None),
 (48, 'BA', None),
 (49, 'TN', None),
 (50, 'WA', None),
 (51, 'MA', None),
 (52, 'AL', None),
 (53, 'SY', None),
 (54, 'TI', None),
 (55, 'ON', None),
 (56, 'BE', None),
 (57, 'CO', None),
 (58, 'AS', None),
 (59, 'VA', None),
 (60, 'AZ', None),
 (61, 'ZZ', None),
 (62, 'PE', None),
 (63, '01', None),
 (64, 'ND', None),
 (65, 'KE', None),
 (66, 'H', None),
 (67, 'GU', None),
 (68, 'AE', None),
 (69, 'IR', None),
 (70, 'HI', None),
 (71, 'NL', None),
 (72, 'HA', None),
 (73, 'IN', None),
 (74, 'NE', None),
 (75, 'FL', None),
 (76, 'ME', None),
 (77, 'UN', None),
 (78, 'N/', None),
 (79, 'SD', None),
 (80, 'BL', None),
 (81, 'U*', None),
 (82, 'OT', None),
 (83, 'RJ', None),
 (84, 'BW', None),
 (85, 'NJ', None),
 (86, 'MP', None),
 (87, 'UT', None),
 (88, 'CH', None),
 (89, 'SC', None),
 (90, 'VI', None),
 (91, 'ZH', None),
 (92, 'PW', None),
 (93, 'BO', None),
 (94, 'FM', None),
 (95, 'CA', None),
 (96, 'NB', None),
 (97, 'LO', None),
 (98, 'TX', None),
 (99, 'PR', None),
 (100, '81', None),
 (101, 'KY', None),
 (102, 'MB', None),
 (103, 'NM', None),
 (104, 'MS', None),
 (105, "'U", None),
 (106, 'PH', None),
 (107, 'MO', None),
 (108, 'NC', None),
 (109, 'SU', None),
 (110, 'OK', None),
 (111, 'ID', None),
 (112, 'GA', None),
 (113, 'MN', None),
 (114, 'PA', None),
 (115, 'AK', None),
 (116, 'MD', None),
 (117, 'TO', None),
 (118, 'JA', None),
 (119, 'IL', None),
 (120, 'IS', None),
 (121, 'GP', None),
 (122, 'TE', None),
 (123, 'EU', None),
 (124, 'IA', None),
 (125, 'VT', None)]

__From the result, we could see that there are 125 different states in this dataset but united states has only 51 states. This might extra caution when working on the further analysis about states or regions.__

__Region Refering__
Update REGION according the contributor's state. 

Northest(9): Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont, New Jersey, New York, and Pennsylvania

Midwest(12): Illinois, Indiana, Michigan, Ohio, Wisconsin, Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, and South Dakota

South(17): Delaware, Florida, Georgia, Maryland, North Carolina, South Carolina, Virginia, District of Columbia, West Virginia, Alabama, Kentucky, Mississippi, Tennessee, Arkansas, Louisiana, Oklahoma, and Texas

West(13): Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah, Wyoming, Alaska, California, Hawaii, Oregon, and Washington

In [3]:
%%sql
UPDATE CONTRIBUTOR_LOCATION
SET REGION = CASE
            WHEN STATE in ('CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA')
            THEN 'Northeast'
            WHEN STATE in ('IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD')
            THEN 'Midwest'
            WHEN STATE in ('DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX')
            THEN 'South'
            WHEN STATE in ('AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA')
            THEN 'West'
            Else 'None'
            End

 * postgresql://student@/final_project_yu
125 rows affected.


[]

In [4]:
%%sql
alter table contribution_fact_ref
add column CONTRIBUTOR_LOCATION_KEY integer,
add constraint fk_contributor_location
    foreign key (CONTRIBUTOR_LOCATION_KEY)
    references CONTRIBUTOR_LOCATION (CONTRIBUTOR_LOCATION_KEY);

 * postgresql://student@/final_project_yu
Done.


[]

In [5]:
%%sql
update contribution_fact_ref
set CONTRIBUTOR_LOCATION_KEY = CONTRIBUTOR_LOCATION.CONTRIBUTOR_LOCATION_KEY
FROM CONTRIBUTOR_LOCATION
WHERE contribution_fact_ref.STATE = CONTRIBUTOR_LOCATION.STATE
;

 * postgresql://student@/final_project_yu
60501054 rows affected.


[]

In [10]:
%%sql
select * from contribution_fact_ref
limit 5
;

 * postgresql://student@/final_project_yu
5 rows affected.


[('C00027466', 'CARIASO, SEGUNDO', 'NY', 'RETIRED', Decimal('10022020'), Decimal('3.00'), 'C00694323', Decimal('4111920201959287261'), 'IND_COM', 2, 186, 18897, 10),
 ('C00027466', 'ARNOLD, CRAIG', 'MI', 'TECHNICIAN', Decimal('10022020'), Decimal('20.00'), 'C00694323', Decimal('4111920201959281533'), 'IND_COM', 2, 186, 18897, 28),
 ('C00027466', 'CUTHBERTSON, SYBIL', 'FL', 'RETIRED', Decimal('10022020'), Decimal('30.00'), 'C00694323', Decimal('4111920201959281535'), 'IND_COM', 2, 186, 18897, 75),
 ('C00027466', 'OLSON, TOM F', 'CA', 'RETIRED', Decimal('10022020'), Decimal('100.00'), None, Decimal('4111920201959264192'), 'IND_COM', 2, 186, 18897, 95),
 ('C00027466', 'PUCHNER, PETER J', 'NY', 'RETIRED', Decimal('10022020'), Decimal('75.00'), None, Decimal('4111920201959264517'), 'IND_COM', 2, 186, 18897, 10)]

### 4.5 Dimension 5 - Contributor Occupation

In [11]:
%%sql
DROP TABLE IF EXISTS CONTRIBUTOR_OCCUPATION cascade;

CREATE TABLE CONTRIBUTOR_OCCUPATION (
    CONTRIBUTOR_OCCUPATION_KEY SERIAL PRIMARY KEY,
    OCCUPATION VARCHAR(38)
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [12]:
%%sql
insert into CONTRIBUTOR_OCCUPATION (OCCUPATION)
SELECT DISTINCT OCCUPATION as OCCUPATION
from CONTRIBUTION_FACT_REF;

 * postgresql://student@/final_project_yu
502977 rows affected.


[]

In [13]:
%%sql
alter table contribution_fact_ref
add column CONTRIBUTOR_OCCUPATION_KEY integer,
add constraint fk_contributor_OCCUPATION
    foreign key (CONTRIBUTOR_OCCUPATION_KEY)
    references CONTRIBUTOR_OCCUPATION (CONTRIBUTOR_OCCUPATION_KEY);

 * postgresql://student@/final_project_yu
Done.


[]

In [14]:
%%sql
update contribution_fact_ref
set CONTRIBUTOR_OCCUPATION_KEY = CONTRIBUTOR_OCCUPATION.CONTRIBUTOR_OCCUPATION_KEY
FROM CONTRIBUTOR_OCCUPATION
WHERE contribution_fact_ref.OCCUPATION = CONTRIBUTOR_OCCUPATION.OCCUPATION
;

 * postgresql://student@/final_project_yu
56182997 rows affected.


[]

In [15]:
%%sql
select * from contributor_occupation
limit 5
;

 * postgresql://student@/final_project_yu
5 rows affected.


[(1, 'ELECTRONIS TECHICIAN'),
 (2, 'SUBSTATION/SWITCHING TECH 1ST CLASS'),
 (3, 'NETWORK TECHNICAL SPECIALIST'),
 (4, 'CONSTRUCTION/CONSULTING'),
 (5, 'READY RESERVE CUSTOMER SERVICE AGENT')]

In [16]:
%%sql
select * from contribution_fact_ref
limit 5
;

 * postgresql://student@/final_project_yu
5 rows affected.


[('C00455357', 'H & S SIGNS', None, None, Decimal('9152011'), Decimal('0.00'), 'P00003392', Decimal('2120520171482672530'), 'COM_CAN', 1, 394, None, None, None),
 ('C00455357', 'H & S SIGNS', None, None, Decimal('9152011'), Decimal('0.00'), 'P00003392', Decimal('2120520171482672530'), 'COM_COM', 3, 394, None, None, None),
 ('C00401224', 'BERNARD, LAURA', 'MA', None, Decimal('10022020'), Decimal('5.00'), 'C00674093', Decimal('4111920201949947463'), 'IND_COM', 2, 186, 28929, 51, None),
 ('C00401224', 'BERNARD, LAURA', 'MA', None, Decimal('10022020'), Decimal('15.00'), 'C00674093', Decimal('4111920201949947464'), 'IND_COM', 2, 186, 28929, 51, None),
 ('C00401224', 'HENDRIKS, PRISCILLA', 'BC', None, Decimal('10022020'), Decimal('50.00'), 'C00010603', Decimal('4111920201949863375'), 'IND_COM', 2, 186, 28929, 14, None)]

### 4.6 Dimension 6 - Contributor ID

In [17]:
%%sql
DROP TABLE IF EXISTS CONTRIBUTOR_ID cascade;

CREATE TABLE CONTRIBUTOR_ID (
    CONTRIBUTOR_ID_KEY SERIAL PRIMARY KEY,
    ID VARCHAR(9)
);

 * postgresql://student@/final_project_yu
Done.
Done.


[]

In [18]:
%%sql
insert into CONTRIBUTOR_ID (ID)
SELECT DISTINCT OTHER_ID as ID
from CONTRIBUTION_FACT_REF;

 * postgresql://student@/final_project_yu
15353 rows affected.


[]

In [19]:
%%sql
alter table contribution_fact_ref
add column CONTRIBUTOR_ID_KEY integer,
add constraint fk_contributor_id
    foreign key (CONTRIBUTOR_ID_KEY)
    references CONTRIBUTOR_ID (CONTRIBUTOR_ID_KEY);

 * postgresql://student@/final_project_yu
Done.


[]

In [21]:
%%sql
update contribution_fact_ref
set CONTRIBUTOR_ID_KEY = CONTRIBUTOR_ID.CONTRIBUTOR_ID_KEY
FROM CONTRIBUTOR_ID
WHERE contribution_fact_ref.other_id = CONTRIBUTOR_ID.id
;

 * postgresql://student@/final_project_yu
39807757 rows affected.


[]

In [6]:
%%sql
select * from contribution_fact_ref
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[('C00206136', 'KINZINGER FOR CONGRESS', 'VA', None, Decimal('2272015'), Decimal('2500.00'), 'C00458877', Decimal('4032020151240893826'), 'COM_COM', 3, 127, 3917, 59, None, 13369, None),
 ('C00089136', 'PORTMAN FOR SENATE COMMITTEE', 'OH', None, Decimal('2272015'), Decimal('1000.00'), 'C00458463', Decimal('4031120151240622514'), 'COM_COM', 3, 127, 16752, 8, None, 10004, None),
 ('C00089136', 'RENEE ELLMERS FOR CONGRESS COMMITTEE', 'NC', None, Decimal('2272015'), Decimal('1000.00'), 'C00471896', Decimal('4031120151240622515'), 'COM_COM', 3, 127, 16752, 108, None, 789, None),
 ('C00089136', 'JASON SMITH FOR CONGRESS', 'MO', None, Decimal('2272015'), Decimal('2000.00'), 'C00541862', Decimal('4031120151240622505'), 'COM_COM', 3, 127, 16752, 107, None, 1283, None),
 ('C00247569', 'TENN POLITICAL ACTION COMMITTEE', 'VA', None, Decimal('2272015'), Decimal('5000.00'), 'C00388421', Decimal('4031920151240874690'), 'COM_COM', 3, 127, 2984, 59, None, 4022, None)]

## 5. Drop unused column

In [7]:
%%sql
alter table contribution_fact_ref
drop column cmte_id,
drop column name,
drop column state,
drop column occupation,
drop column transaction_dt,
drop column other_id,
drop column contribution_type,
;

 * postgresql://student@/final_project_yu
Done.


[]

In [9]:
%%sql
select * from contribution_fact_ref
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('2500.00'), Decimal('4032020151240893826'), 3, 127, 3917, 59, None, 13369),
 (Decimal('1000.00'), Decimal('4031120151240622514'), 3, 127, 16752, 8, None, 10004),
 (Decimal('1000.00'), Decimal('4031120151240622515'), 3, 127, 16752, 108, None, 789),
 (Decimal('2000.00'), Decimal('4031120151240622505'), 3, 127, 16752, 107, None, 1283),
 (Decimal('5000.00'), Decimal('4031920151240874690'), 3, 127, 2984, 59, None, 4022)]

__Change the name of table into standardized format:__
+ Fact table - contribution_fact
+ Dimension 1 - TYPE
+ Dimension 2 - DATE
+ Dimension 3 - BENEFICIARY
+ Dimension 4 - CONTRIBUTOR_ID
+ Dimension 5 - CONTIRBUTOR_OCCUPATION
+ Dimension 6 - CONTRIBUTOR_LOCATION

In [10]:
%%sql
alter table TYPE_V2 RENAME TO TYPE;

 * postgresql://student@/final_project_yu
Done.


[]

In [11]:
%%sql
alter table DATE_V2 RENAME TO DATE;

 * postgresql://student@/final_project_yu
Done.


[]

In [12]:
%%sql
alter table BENEFICIARY_V2 RENAME TO BENEFICIARY;

 * postgresql://student@/final_project_yu
Done.


[]

In [13]:
%%sql
alter table CONTRIBUTION_FACT_REF RENAME TO CONTRIBUTION_FACT;

 * postgresql://student@/final_project_yu
Done.


[]

__ __

# Part C: Answer Question 

# Question 1: Candidates received most contribution by individual (top 5)

## 1.1 - Total amount of contributions by individual

### In year 2016

In [15]:
%%sql
select TTL_INDIV_CONTRIB, cand.cand_name, cand.cand_id, cmte.cmte_id, e.CAND_PTY_AFFILIATION from all_candidate
join coverage_year as c
on c.coverage_year_key = all_candidate.coverage_year_key
join candidate_info as cand
on cand.info_key = all_candidate.info_key
join cmte_link as cmte
on cmte.cmte_link_key = all_candidate.cmte_link_key
join election as e
on e.election_key = all_candidate.election_key
where c.year = 2016
order by TTL_INDIV_CONTRIB desc
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('405664230.47'), 'CLINTON, HILLARY RODHAM / TIMOTHY MICHAEL KAINE', 'P00003392', 'C00577395', 'DEM'),
 (Decimal('231815008.02'), 'SANDERS, BERNARD', 'P60007168', 'C00588434', 'DEM'),
 (Decimal('133622961.93'), 'TRUMP, DONALD J.', 'P80001571', 'C00580100', 'REP'),
 (Decimal('92036251.55'), 'CRUZ, RAFAEL EDWARD "TED"', 'P60006111', 'C00615401', 'REP'),
 (Decimal('63461402.63'), 'CARSON, BENJAMIN S SR MD', 'P60005915', 'C00573519', 'REP')]

### In year 2020

In [16]:
%%sql
select TTL_INDIV_CONTRIB, cand.cand_name, cand.cand_id, cmte.cmte_id, e.CAND_PTY_AFFILIATION from all_candidate
join coverage_year as c
on c.coverage_year_key = all_candidate.coverage_year_key
join candidate_info as cand
on cand.info_key = all_candidate.info_key
join cmte_link as cmte
on cmte.cmte_link_key = all_candidate.cmte_link_key
join election as e
on e.election_key = all_candidate.election_key
where c.year = 2020
order by TTL_INDIV_CONTRIB desc
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('719798548.33'), 'BIDEN, JOSEPH R JR', 'P80000722', 'C00703975', 'DEM'),
 (Decimal('316611498.84'), 'TRUMP, DONALD J.', 'P80001571', 'C00580100', 'REP'),
 (Decimal('202554495.98'), 'SANDERS, BERNARD', 'P60007168', 'C00588434', 'DEM'),
 (Decimal('115892704.99'), 'WARREN, ELIZABETH', 'P00009621', 'C00693234', 'DEM'),
 (Decimal('107645931.99'), 'HARRISON, JAIME', 'S0SC00289', 'C00696153', 'DEM')]

__Compare with year 2016 and year 2020:__
+ Since 2020 is the mid-term president election, that is why 4 out 5 for in list 2020 is democratic candidiate while 2016 list have both republican and democrat candidate.
+ Although we have convid_19 in 2020, the total individual contribution amount does not seem  to be affected by the pandemic. On the contrary, the amounts recevied by each candidate in top 5 are way larger than that of in year 2016 viewing from ranking.
+ Specifically, if we compare Biden's amount 719798548.33 and Trump's amount 316611498.84. Biden received almost double than Trump.
+ If comparing Trump's individual contribution receipts, he gain more in year 2020 than in year 2016. In year 2020, he received 719798548.33 and in year 2016, he received 316611498.84.


|Total indiv contribution | Year 2020          | Year 2016                |
|-------------------------|--------------------|--------------------------|
|No. 1                    | BIDEN, JOSEPH R JR | CLINTON, HILLARY RODHAM  |
|No. 2                    | TRUMP, DONALD J.   | SANDERS, BERNARD         |
|No. 3                    | SANDERS, BERNARD   | TRUMP, DONALD J.         |
|No. 4                    | WARREN, ELIZABETH  | CRUZ, RAFAEL EDWARD "TED"|
|No. 5                    | HARRISON, JAIME    | CARSON, BENJAMIN S SR MD |

## 1.2 - 2020 Biden vs Trump Break out - By Swing states and By Regions

### Preparation
__We want to use the Committee_ID of Trump, Clinton and Biden to look into the detail of contribution breakdown.__ 

In [54]:
%%sql
select distinct CMTE_ID, CAND_NAME from ALL_CANDIDATE
join cmte_link as c
on c.cmte_link_key = ALL_CANDIDATE.cmte_link_key
join candidate_info as cand
on cand.info_key  = ALL_CANDIDATE.info_key
where cand.CAND_NAME LIKE '%CLINTON%'

 * postgresql://student@/final_project_yu
3 rows affected.


[('C00358895', 'CLINTON, HILLARY RODHAM'),
 ('C00577395', 'CLINTON, HILLARY RODHAM / TIMOTHY MICHAEL KAINE'),
 ('C00706762', 'MORGAN, CLINTON WESLEY')]

In [55]:
%%sql
select distinct CMTE_ID, CAND_NAME from ALL_CANDIDATE
join cmte_link as c
on c.cmte_link_key = ALL_CANDIDATE.cmte_link_key
join candidate_info as cand
on cand.info_key  = ALL_CANDIDATE.info_key
where cand.CAND_NAME LIKE '%BIDEN%'

 * postgresql://student@/final_project_yu
2 rows affected.


[('C00431445', 'OBAMA, BARACK / JOSEPH R. BIDEN'),
 ('C00703975', 'BIDEN, JOSEPH R JR')]

In [56]:
%%sql
select distinct CMTE_ID, CAND_NAME from ALL_CANDIDATE
join cmte_link as c
on c.cmte_link_key = ALL_CANDIDATE.cmte_link_key
join candidate_info as cand
on cand.info_key  = ALL_CANDIDATE.info_key
where cand.CAND_NAME LIKE '%TRUMP%'

 * postgresql://student@/final_project_yu
1 rows affected.


[('C00580100', 'TRUMP, DONALD J.')]

__We also want to check out that how many contirbutions are maded by individual and among those individuals how many reveal they state information__ 

In [6]:
%%sql
select count(*) from contribution_fact
join TYPE as t
on t.type_key = contribution_fact.type_key
where t.contribution_type = 'IND_COM';

 * postgresql://student@/final_project_yu
1 rows affected.


[(53765647,)]

In [7]:
%%sql
select count(*) from contribution_fact
join TYPE as t
on t.type_key = contribution_fact.type_key
where t.contribution_type = 'IND_COM' and contributor_location_key is not null;

 * postgresql://student@/final_project_yu
1 rows affected.


[(53731715,)]

In [8]:
53731715/53765647

0.9993688906970654

__We could see that 99.94% of the individual contributor has been recorded with state information. We therefore could say that our analysis on contribution breakdown by state and region is meaningful.__

### a. Digging on Swing States

The inclusion of Swing States is based on website ‘https://www.marieclaire.com/politics/a31142244/swing-states-2020-election/’ in which we are going to consider:
+ AZ - Arizona
+ CO - Colorado
+ FL - Florida
+ GA - Georgia
+ IA - Iowa
+ MI - Michigan
+ MN - Minnesota
+ NE - Nebraska
+ NH - New Hampshire
+ NC - North Carolina
+ PA - Pennsylvania
+ VA - Virginia
+ WI - Wisconsin

#### Trump

In [78]:
%%sql
select sum(transaction_amt),l.state  from contribution_fact
join contributor_location as l
on l.contributor_location_key = contribution_fact.contributor_location_key
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2020 and b.cmte_id = 'C00580100' and t.contribution_type = 'IND_COM' 
and l.state in ('AZ','CO','FL','GA','IA','MI','MN','NE','NH','NC','PA','VA','WI')
group by l.state
order by l.state
;

 * postgresql://student@/final_project_yu
13 rows affected.


[(Decimal('3340795.00'), 'AZ'),
 (Decimal('2375302.00'), 'CO'),
 (Decimal('10932804.00'), 'FL'),
 (Decimal('3562640.00'), 'GA'),
 (Decimal('675012.00'), 'IA'),
 (Decimal('2636786.00'), 'MI'),
 (Decimal('1409440.00'), 'MN'),
 (Decimal('2860235.00'), 'NC'),
 (Decimal('507518.00'), 'NE'),
 (Decimal('427061.00'), 'NH'),
 (Decimal('3224306.00'), 'PA'),
 (Decimal('32485681.00'), 'VA'),
 (Decimal('1402660.00'), 'WI')]

#### Biden

In [79]:
%%sql
select sum(transaction_amt),l.state  from contribution_fact
join contributor_location as l
on l.contributor_location_key = contribution_fact.contributor_location_key
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2020 and b.cmte_id = 'C00703975' and t.contribution_type = 'IND_COM' 
and l.state in ('AZ','CO','FL','GA','IA','MI','MN','NE','NH','NC','PA','VA','WI')
group by l.state
order by l.state
;

 * postgresql://student@/final_project_yu
13 rows affected.


[(Decimal('5801123.00'), 'AZ'),
 (Decimal('10065836.00'), 'CO'),
 (Decimal('18994947.00'), 'FL'),
 (Decimal('6830479.00'), 'GA'),
 (Decimal('1671397.00'), 'IA'),
 (Decimal('7210062.00'), 'MI'),
 (Decimal('6261664.00'), 'MN'),
 (Decimal('8380757.00'), 'NC'),
 (Decimal('823380.00'), 'NE'),
 (Decimal('2069673.00'), 'NH'),
 (Decimal('13998377.00'), 'PA'),
 (Decimal('14547968.00'), 'VA'),
 (Decimal('3702043.00'), 'WI')]

In [3]:
from IPython.display import Image
Image(url = 'https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/swing.png')


+ We could see that generally speaking Biden received more funds from individual than Trump except for VA.
+ Consider the wealthiness of each state and different type of the supporters, receveid more funds from individual does not necessary represent that more supports

### b. By Region
#### Trump

In [62]:
%%sql
select sum(transaction_amt),l.region  from contribution_fact
join contributor_location as l
on l.contributor_location_key = contribution_fact.contributor_location_key
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2020 and b.cmte_id = 'C00580100' and t.contribution_type = 'IND_COM'
group by l.region
order by l.region
;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('16768291.00'), 'Midwest'),
 (Decimal('86253.00'), 'None'),
 (Decimal('12657487.00'), 'Northeast'),
 (Decimal('75851310.00'), 'South'),
 (Decimal('29063029.00'), 'West')]

#### Biden

In [63]:
%%sql
select sum(transaction_amt),l.region  from contribution_fact
join contributor_location as l
on l.contributor_location_key = contribution_fact.contributor_location_key
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2020 and b.cmte_id = 'C00703975' and t.contribution_type = 'IND_COM'
group by l.region
order by l.region
;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('49687643.00'), 'Midwest'),
 (Decimal('1804885.00'), 'None'),
 (Decimal('96426838.00'), 'Northeast'),
 (Decimal('109686051.00'), 'South'),
 (Decimal('135784838.00'), 'West')]

__Conclusion__

+ For __Trump__, the order from most to least based on individual contribution amount is __South > West > Midwest > Northeast__
    + The result is reasonable because most of the South region is under control of Republicans.



+ For __Biden__, the order from most to least based on individual contribution amount is __West > South > Northeast > Midwest.__
    + From the election result this year, Biden takes all west coast states. Therefore, Biden recevied most inidividual contribution from West is reasonable.

### 1.3 Compare contribution from individual received by Trump in Year 2020 and 2016 among regions

In [64]:
%%sql
select sum(transaction_amt),l.region  from contribution_fact
join contributor_location as l
on l.contributor_location_key = contribution_fact.contributor_location_key
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2016 and b.cmte_id = 'C00580100' and t.contribution_type = 'IND_COM'
group by l.region
order by l.region
;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('7476911.00'), 'Midwest'),
 (Decimal('62697.00'), 'None'),
 (Decimal('24952422.00'), 'Northeast'),
 (Decimal('22764873.00'), 'South'),
 (Decimal('11720387.00'), 'West')]

__Conclusion:__
+ The ranking from high to low of total individual contribution received by Trump among regions is __Northeast > South > West > Midwest__ in year __2016__. Let's recope the ranking from year 2020: __South > West > Midwest > Northeast__.
    + We could see that Northeast dropped from the top to the least from year 2016 to year 2020.
    + Based on region explanation, Northeast contains Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont, New Jersey, New York, and Pennsylvania


+ From the result we could see that, Trump gain more contributions by individual from Midwest, South and West in year 2020 compared with that of 2016. Northeast has less contributions in year 2020. 

__ __

## Question 2 - Top 5 Committees that received most funds

### 1. In Year 2016

In [74]:
%%sql
select sum(TRANSACTION_AMT) as sum_amount , b.CMTE_ID, b.CMTE_NAME, b.CMTE_PTY_AFFILIATION from contribution_fact

join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY

join date as d
on d.date_key = contribution_fact.date_key

join TYPE as t
on t.type_key = contribution_fact.type_key

where d.year = 2016 
and t.contribution_type != 'COM_CAN'
group by b.CMTE_ID, B.CMTE_NAME, b.CMTE_PTY_AFFILIATION 
order by sum_amount desc
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('762234257.00'), 'C00586537', 'HILLARY VICTORY FUND', None),
 (Decimal('532313694.00'), 'C00010603', 'DNC SERVICES CORP / DEMOCRATIC NATIONAL COMMITTEE', 'DEM'),
 (Decimal('499011630.00'), 'C00575795', 'HILLARY FOR AMERICA', 'DEM'),
 (Decimal('306309619.00'), 'C00003418', 'REPUBLICAN NATIONAL COMMITTEE', 'REP'),
 (Decimal('300202434.00'), 'C00495861', 'PRIORITIES USA ACTION', None)]

### 2. In Year 2020

In [75]:
%%sql
select sum(TRANSACTION_AMT) as sum_amount , b.CMTE_ID, b.CMTE_NAME, b.CMTE_PTY_AFFILIATION from contribution_fact

join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY

join date as d
on d.date_key = contribution_fact.date_key

join TYPE as t
on t.type_key = contribution_fact.type_key

where d.year = 2020
and t.contribution_type != 'COM_CAN'
group by b.CMTE_ID, B.CMTE_NAME, b.CMTE_PTY_AFFILIATION 
order by sum_amount desc
limit 5;

 * postgresql://student@/final_project_yu
5 rows affected.


[(Decimal('931048458.00'), 'C00694323', 'WINRED', None),
 (Decimal('908683536.00'), 'C00728154', 'MIKE BLOOMBERG 2020, INC.', 'DEM'),
 (Decimal('902517278.00'), 'C00703975', 'BIDEN FOR PRESIDENT', 'DEM'),
 (Decimal('851044952.00'), 'C00401224', 'ACTBLUE', None),
 (Decimal('510371770.00'), 'C00003418', 'REPUBLICAN NATIONAL COMMITTEE', 'REP')]

__Conclusion:__
+ The 2020 election is more than twice as expensive as the runner up, the 2016 election. In fact, this year’s election will see more spending than the previous two presidential election cycles combined. The pademic in 2020 do not affect much of the funding.

+ Contribution received by committees reflects the election result in some way, abide objective factors still needed to be concerned. For example, in the year 2016, while the Democrat committees raise more funds than the Republican committees among the top 5 figures, the Democrat party still lose the election due to the scandal. In the year 2020, the data of two-party are similar, reflected in the election vote and the stalemate lasted several weeks before it finally ended.

__ __

# Question 3 - 

## 1. Which five states have the most candidate offices? 


__Here, we excluded candidate office state labelled as 'US' because that's is not a state. There were showing the candidates has their election_office labelled as US, including Donald Trump and Kanye West. We assume that either they don't want to expose information about their offices. Here, we excluded candidate office state labelled as 'US' because that's is not a state.__

### a. In year 2020


In [4]:
%%sql
select o.CAND_OFFICE_STATE,count(*) from all_candidate
JOIN Election as e
on e.election_key = all_candidate.election_key
JOIN OFFICE AS o
ON o.office_key = all_candidate.office_key
JOIN COVERAGE_YEAR AS c
on c.coverage_year_key = all_candidate.coverage_year_key
where c.YEAR = 2020 and o.CAND_OFFICE_STATE != 'US'
group BY o.CAND_OFFICE_STATE
order by count desc
limit 5
;

 * postgresql://student@/final_project_yu
5 rows affected.


[('TX', 291), ('CA', 276), ('FL', 202), ('NY', 186), ('GA', 128)]

In [5]:
from IPython.display import Image
Image(url = 'https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2020%20states.png')

### b. In year 2016

In [6]:
%%sql
select o.CAND_OFFICE_STATE,count(*) from all_candidate
JOIN Election as e
on e.election_key = all_candidate.election_key
JOIN OFFICE AS o
ON o.office_key = all_candidate.office_key
JOIN COVERAGE_YEAR AS c
on c.coverage_year_key = all_candidate.coverage_year_key
where c.YEAR = 2016 and o.CAND_OFFICE_STATE != 'US'
group BY o.CAND_OFFICE_STATE
order by count desc
limit 5
;

 * postgresql://student@/final_project_yu
5 rows affected.


[('CA', 242), ('FL', 190), ('NY', 130), ('TX', 128), ('NC', 91)]

In [8]:
from IPython.display import Image
Image(url = 'https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2016%20states.png')


__Conclusion__:
+ Although the ranking are different,CA,FL,NY and TX appears in both results but GA only appear in 2020 and NC only appear in 2016. 
+ Also, it is noticed by our group that the number of offices has an increasing trend.

## 2. Among those top 5 states with the most candidates offices, what are the distribution of parties in 2020 and 2016?

### a. In year 2020

In [10]:
%%sql
select e.cand_pty_affiliation,o.cand_office_state,count(*) from all_candidate
JOIN Election as e
on e.election_key = all_candidate.election_key
JOIN OFFICE AS o
ON o.office_key = all_candidate.office_key
JOIN COVERAGE_YEAR AS c
on c.coverage_year_key = all_candidate.coverage_year_key
where (o.cand_office_state='TX'
or o.cand_office_state='CA'
or o.cand_office_state='FL'
or o.cand_office_state='GA'
or o.cand_office_state='NY')
and c.year = 2020
group BY e.cand_pty_affiliation,o.cand_office_state
order by o.cand_office_state
limit 40

;

 * postgresql://student@/final_project_yu
38 rows affected.


[('DEM', 'CA', 145),
 ('GRE', 'CA', 1),
 ('IND', 'CA', 3),
 ('NNE', 'CA', 1),
 ('NON', 'CA', 1),
 ('NPA', 'CA', 3),
 ('REP', 'CA', 122),
 ('DEM', 'FL', 68),
 ('IND', 'FL', 3),
 ('LIB', 'FL', 1),
 ('LPF', 'FL', 1),
 ('NPA', 'FL', 5),
 ('OTH', 'FL', 1),
 ('REP', 'FL', 122),
 ('W', 'FL', 1),
 ('DEM', 'GA', 51),
 ('GRE', 'GA', 2),
 ('IND', 'GA', 3),
 ('LIB', 'GA', 4),
 ('REP', 'GA', 68),
 ('CRV', 'NY', 1),
 ('DEM', 'NY', 106),
 ('GRE', 'NY', 1),
 ('IND', 'NY', 6),
 ('LIB', 'NY', 3),
 ('NNE', 'NY', 1),
 ('OTH', 'NY', 1),
 ('REP', 'NY', 64),
 ('SAM', 'NY', 1),
 ('W', 'NY', 1),
 ('WFP', 'NY', 1),
 ('DEM', 'TX', 112),
 ('GRE', 'TX', 1),
 ('IND', 'TX', 8),
 ('LBU', 'TX', 1),
 ('LIB', 'TX', 8),
 ('REP', 'TX', 160),
 ('W', 'TX', 1)]

In [11]:
from IPython.display import Image
Image(url = 'https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2020%20office%20dist.png')

### b. In Year 2016

In [9]:
%%sql
select e.cand_pty_affiliation,o.cand_office_state,count(*) from all_candidate
JOIN Election as e
on e.election_key = all_candidate.election_key
JOIN OFFICE AS o
ON o.office_key = all_candidate.office_key
JOIN COVERAGE_YEAR AS c
on c.coverage_year_key = all_candidate.coverage_year_key
where (o.cand_office_state='TX'
or o.cand_office_state='CA'
or o.cand_office_state='FL'
or o.cand_office_state='NC'
or o.cand_office_state='NY')
and c.year = 2016
group BY e.cand_pty_affiliation,o.cand_office_state
order by o.cand_office_state
limit 35
;


 * postgresql://student@/final_project_yu
34 rows affected.


[('DEM', 'CA', 118),
 ('GRE', 'CA', 1),
 ('IND', 'CA', 9),
 ('NNE', 'CA', 3),
 ('OTH', 'CA', 1),
 ('REP', 'CA', 110),
 ('DEM', 'FL', 73),
 ('IND', 'FL', 3),
 ('LIB', 'FL', 4),
 ('LPF', 'FL', 1),
 ('NNE', 'FL', 1),
 ('NPA', 'FL', 4),
 ('OTH', 'FL', 2),
 ('REP', 'FL', 100),
 ('UNK', 'FL', 1),
 ('W', 'FL', 1),
 ('DEM', 'NC', 38),
 ('LIB', 'NC', 2),
 ('REP', 'NC', 51),
 ('DEM', 'NY', 68),
 ('GRE', 'NY', 2),
 ('IND', 'NY', 3),
 ('LIB', 'NY', 2),
 ('N/A', 'NY', 1),
 ('NNE', 'NY', 1),
 ('NPA', 'NY', 1),
 ('OTH', 'NY', 1),
 ('REP', 'NY', 50),
 ('WFP', 'NY', 1),
 ('DEM', 'TX', 48),
 ('GRE', 'TX', 1),
 ('IND', 'TX', 1),
 ('LIB', 'TX', 1),
 ('REP', 'TX', 77)]

In [12]:
from IPython.display import Image
Image(url = 'https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2016%20office%20dist.png')

__Conclusion:__
+ Not suprisingly, Democrat and Republican have the most candidates among those five states.

__ __

# Queston 4 - Contribution by individual and committee breakdown by States

## 1. Committees contribution in 2016

In [19]:
%%sql
select b.state as State, sum(a.transaction_amt) as Contribution_Amount 
from CONTRIBUTION_FACT a 
join CONTRIBUTOR_LOCATION b on a.CONTRIBUTOR_LOCATION_KEY = b.CONTRIBUTOR_LOCATION_KEY 
join TYPE c on a.Type_Key = c.TYPE_key
join date d on a.date_key = d.date_key
where (c.CONTRIBUTION_TYPE = 'COM_COM' or c.CONTRIBUTION_TYPE = 'COM_CAN')
        and b.state in ('CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA',
                       'IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD',
                       'DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX',
                       'AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA')
        and d.year = 2016
group by b.state
order by sum(a.transaction_amt) desc

 * postgresql://student@/final_project_yu
51 rows affected.


[('DC', Decimal('2168263728.00')),
 ('VA', Decimal('964448865.00')),
 ('NY', Decimal('955015237.00')),
 ('MD', Decimal('530373073.00')),
 ('CA', Decimal('493200774.00')),
 ('MA', Decimal('293524875.00')),
 ('OH', Decimal('197590108.00')),
 ('FL', Decimal('197221216.00')),
 ('TX', Decimal('193652305.00')),
 ('IL', Decimal('129466305.00')),
 ('PA', Decimal('120330362.00')),
 ('GA', Decimal('99450277.00')),
 ('WI', Decimal('82589443.00')),
 ('IA', Decimal('79762603.00')),
 ('CO', Decimal('77568905.00')),
 ('MO', Decimal('75770390.00')),
 ('NC', Decimal('72345780.00')),
 ('NV', Decimal('59740747.00')),
 ('NJ', Decimal('56163191.00')),
 ('NH', Decimal('54122854.00')),
 ('AZ', Decimal('52463965.00')),
 ('MI', Decimal('51542336.00')),
 ('IN', Decimal('50464789.00')),
 ('MN', Decimal('49140494.00')),
 ('SC', Decimal('45403491.00')),
 ('WA', Decimal('38918717.00')),
 ('LA', Decimal('38241602.00')),
 ('TN', Decimal('36745104.00')),
 ('CT', Decimal('32469797.00')),
 ('KY', Decimal('30870388.00')),
 ('OR', Decimal('28246749.00')),
 ('UT', Decimal('27684609.00')),
 ('AR', Decimal('25717737.00')),
 ('KS', Decimal('24146979.00')),
 ('OK', Decimal('19484437.00')),
 ('WV', Decimal('16377414.00')),
 ('WY', Decimal('15832223.00')),
 ('MS', Decimal('15827492.00')),
 ('AL', Decimal('15467005.00')),
 ('SD', Decimal('15306096.00')),
 ('ME', Decimal('13793225.00')),
 ('ID', Decimal('13671546.00')),
 ('NM', Decimal('12949177.00')),
 ('DE', Decimal('11270519.00')),
 ('MT', Decimal('11203998.00')),
 ('NE', Decimal('10676743.00')),
 ('AK', Decimal('10635725.00')),
 ('RI', Decimal('10275282.00')),
 ('ND', Decimal('6816981.00')),
 ('VT', Decimal('5340045.00')),
 ('HI', Decimal('4855202.00'))]

In [27]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Committee+Contribution+2016.png")


In [28]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Committee+Contribution+2016+Zoomed.png")

__In 2016, the top 5 states by committee contribution are Washington D.C., Virginia, New York, Maryland, and California.__

## 2. Individual contribution in 2016

In [20]:
%%sql
select b.state as State, sum(a.transaction_amt) as Contribution_Amount 
from CONTRIBUTION_FACT a 
join CONTRIBUTOR_LOCATION b on a.CONTRIBUTOR_LOCATION_KEY = b.CONTRIBUTOR_LOCATION_KEY 
join TYPE c on a.Type_Key = c.TYPE_key
join date d on a.date_key = d.date_key
where c.CONTRIBUTION_TYPE = 'IND_COM' 
        and b.state in ('CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA',
                       'IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD',
                       'DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX',
                       'AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA')
        and d.year = 2016
group by b.state
order by sum(a.transaction_amt) desc

 * postgresql://student@/final_project_yu
51 rows affected.


[('CA', Decimal('586823672.00')),
 ('NY', Decimal('486952834.00')),
 ('DC', Decimal('308431713.00')),
 ('FL', Decimal('235998096.00')),
 ('TX', Decimal('226197638.00')),
 ('IL', Decimal('205413113.00')),
 ('VA', Decimal('133211471.00')),
 ('PA', Decimal('130694856.00')),
 ('CT', Decimal('119798701.00')),
 ('NV', Decimal('117950988.00')),
 ('MA', Decimal('98382019.00')),
 ('MD', Decimal('91072910.00')),
 ('OH', Decimal('89625738.00')),
 ('WA', Decimal('66654322.00')),
 ('NJ', Decimal('64150213.00')),
 ('MI', Decimal('60965293.00')),
 ('CO', Decimal('60333141.00')),
 ('GA', Decimal('59199651.00')),
 ('NC', Decimal('54376596.00')),
 ('WI', Decimal('48296787.00')),
 ('AZ', Decimal('46485739.00')),
 ('MO', Decimal('42176197.00')),
 ('MN', Decimal('36908673.00')),
 ('AR', Decimal('34971832.00')),
 ('TN', Decimal('32386391.00')),
 ('LA', Decimal('32273254.00')),
 ('IN', Decimal('30734652.00')),
 ('OK', Decimal('22621753.00')),
 ('OR', Decimal('22479960.00')),
 ('KY', Decimal('20263593.00')),
 ('NE', Decimal('20201009.00')),
 ('KS', Decimal('18057288.00')),
 ('IA', Decimal('14622468.00')),
 ('AL', Decimal('14241222.00')),
 ('SC', Decimal('13637291.00')),
 ('NH', Decimal('12861849.00')),
 ('NM', Decimal('12250010.00')),
 ('UT', Decimal('12067739.00')),
 ('ME', Decimal('10158564.00')),
 ('WY', Decimal('8612937.00')),
 ('ID', Decimal('7884364.00')),
 ('MS', Decimal('7314909.00')),
 ('RI', Decimal('6680584.00')),
 ('VT', Decimal('6667845.00')),
 ('HI', Decimal('6625788.00')),
 ('MT', Decimal('6005810.00')),
 ('AK', Decimal('5804304.00')),
 ('WV', Decimal('5069676.00')),
 ('DE', Decimal('5061406.00')),
 ('SD', Decimal('4366585.00')),
 ('ND', Decimal('3044628.00'))]

In [29]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Individual+Contribution+2016.png")

In [30]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Individual+Contribution+2016+Zoomed.png")

__In 2016, the top five states by individual contribution are California, New York, Washington D.C., Florida, and Texas.__

## 3. Committees contribution in 2020

In [21]:
%%sql
select b.state as State, sum(a.transaction_amt) as Contribution_Amount 
from CONTRIBUTION_FACT a 
join CONTRIBUTOR_LOCATION b on a.CONTRIBUTOR_LOCATION_KEY = b.CONTRIBUTOR_LOCATION_KEY 
join TYPE c on a.Type_Key = c.TYPE_key
join date d on a.date_key = d.date_key
where (c.CONTRIBUTION_TYPE = 'COM_COM' or c.CONTRIBUTION_TYPE = 'COM_CAN')
        and b.state in ('CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA',
                       'IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD',
                       'DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX',
                       'AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA')
        and d.year = 2020
group by b.state
order by sum(a.transaction_amt) desc

 * postgresql://student@/final_project_yu
51 rows affected.


[('DC', Decimal('2177781752.00')),
 ('VA', Decimal('790866248.00')),
 ('CA', Decimal('477983499.00')),
 ('NY', Decimal('450722534.00')),
 ('IL', Decimal('277360094.00')),
 ('MA', Decimal('238766396.00')),
 ('TX', Decimal('204707453.00')),
 ('MD', Decimal('201065997.00')),
 ('OH', Decimal('172816664.00')),
 ('FL', Decimal('169749627.00')),
 ('NV', Decimal('142259159.00')),
 ('GA', Decimal('112425907.00')),
 ('NC', Decimal('100306965.00')),
 ('PA', Decimal('91578886.00')),
 ('MI', Decimal('85161172.00')),
 ('UT', Decimal('66689639.00')),
 ('AZ', Decimal('63819966.00')),
 ('NJ', Decimal('55314732.00')),
 ('IA', Decimal('54305938.00')),
 ('MN', Decimal('53232439.00')),
 ('CO', Decimal('53005871.00')),
 ('WA', Decimal('49449065.00')),
 ('SC', Decimal('39585405.00')),
 ('WI', Decimal('37697968.00')),
 ('TN', Decimal('34461580.00')),
 ('KS', Decimal('31438498.00')),
 ('LA', Decimal('30669506.00')),
 ('IN', Decimal('28509137.00')),
 ('ME', Decimal('27810614.00')),
 ('MO', Decimal('24851378.00')),
 ('CT', Decimal('24264914.00')),
 ('NE', Decimal('24193109.00')),
 ('OR', Decimal('22819054.00')),
 ('AL', Decimal('22706155.00')),
 ('DE', Decimal('22210553.00')),
 ('MT', Decimal('22064603.00')),
 ('KY', Decimal('21196418.00')),
 ('WY', Decimal('18913666.00')),
 ('NH', Decimal('16505154.00')),
 ('NM', Decimal('15671395.00')),
 ('OK', Decimal('14701283.00')),
 ('MS', Decimal('10239572.00')),
 ('AK', Decimal('9793078.00')),
 ('AR', Decimal('9139141.00')),
 ('ID', Decimal('6366502.00')),
 ('WV', Decimal('6119840.00')),
 ('RI', Decimal('5563114.00')),
 ('VT', Decimal('3935364.00')),
 ('SD', Decimal('3912231.00')),
 ('ND', Decimal('3650789.00')),
 ('HI', Decimal('3341287.00'))]

In [31]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Committee+Contribution+2020.png")

In [40]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Committee+Contribution+2020+Zoomed.png")

__In 2020, the top 5 states by committee contribution are Washington D.C., Virginia, California, New York, and Illinois.__

## 4. Individual contribution in 2020

In [22]:
%%sql
select b.state as State, sum(a.transaction_amt) as Contribution_Amount 
from CONTRIBUTION_FACT a 
join CONTRIBUTOR_LOCATION b on a.CONTRIBUTOR_LOCATION_KEY = b.CONTRIBUTOR_LOCATION_KEY 
join TYPE c on a.Type_Key = c.TYPE_key
join date d on a.date_key = d.date_key
where c.CONTRIBUTION_TYPE = 'IND_COM' 
        and b.state in ('CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA',
                       'IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD',
                       'DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX',
                       'AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA')
        and d.year = 2020
group by b.state
order by sum(a.transaction_amt) desc

 * postgresql://student@/final_project_yu
51 rows affected.


[('NY', Decimal('1442583243.00')),
 ('CA', Decimal('1148713390.00')),
 ('TX', Decimal('463274124.00')),
 ('FL', Decimal('398769559.00')),
 ('DC', Decimal('368611458.00')),
 ('VA', Decimal('328249352.00')),
 ('IL', Decimal('268060022.00')),
 ('NV', Decimal('242969170.00')),
 ('MA', Decimal('236361597.00')),
 ('WA', Decimal('169981132.00')),
 ('PA', Decimal('158388530.00')),
 ('GA', Decimal('137720759.00')),
 ('CO', Decimal('122004767.00')),
 ('MD', Decimal('117870543.00')),
 ('MI', Decimal('117445507.00')),
 ('NJ', Decimal('115093299.00')),
 ('AZ', Decimal('105714703.00')),
 ('NC', Decimal('102848422.00')),
 ('OH', Decimal('99917345.00')),
 ('DE', Decimal('85729135.00')),
 ('CT', Decimal('81732359.00')),
 ('MN', Decimal('76751097.00')),
 ('TN', Decimal('75892334.00')),
 ('OR', Decimal('62074557.00')),
 ('IN', Decimal('59742814.00')),
 ('WI', Decimal('58565549.00')),
 ('MO', Decimal('57843230.00')),
 ('WY', Decimal('56840376.00')),
 ('SC', Decimal('47803628.00')),
 ('AL', Decimal('41108262.00')),
 ('LA', Decimal('40371857.00')),
 ('KS', Decimal('39550934.00')),
 ('OK', Decimal('39317763.00')),
 ('AR', Decimal('36448853.00')),
 ('NM', Decimal('36254901.00')),
 ('KY', Decimal('31787506.00')),
 ('IA', Decimal('29628171.00')),
 ('NE', Decimal('27860071.00')),
 ('UT', Decimal('26894578.00')),
 ('ME', Decimal('20452996.00')),
 ('ID', Decimal('20146360.00')),
 ('NH', Decimal('19532054.00')),
 ('MT', Decimal('18901776.00')),
 ('MS', Decimal('16126232.00')),
 ('AK', Decimal('14196159.00')),
 ('HI', Decimal('13996159.00')),
 ('RI', Decimal('11850363.00')),
 ('VT', Decimal('9524846.00')),
 ('WV', Decimal('8275417.00')),
 ('ND', Decimal('7750442.00')),
 ('SD', Decimal('7743536.00'))]

In [33]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Individual+Contribution+2020.png")

In [34]:
from IPython.display import Image
Image(url="https://dmfa-2020-lu.s3.amazonaws.com/Final+Project/Individual+Contribution+2020+Zoomed.png")

__In 2020, the top 5 states by individual contribution are New York, California, Texas, Florida, and Washington D.C.__

### Main takeaways:
1. Committees on the east coast, in states like Washington D.C., New York, and Virginia, contributed more than committees in other parts of the country in the last two elections. On the West coast, California is where committees contributed the most.
2. States that are heavily populated, such as New York, California, Texas, and Florida, except for Washington that has a smaller population, dominated individual contribution in the last two elections.
3. We can see from the heatmap for committee contribution in 2016 and 2020 that the total amount of committee contribution from all states doesn't change much from 2016 and 2020, as the colors are roughly the same. In fact, committees in New York, Virginia, and Maryland contributed noticeably less in 2020 than they did in 2016. 
4. But for individual contributors, 2020 is definitely a bigger year than 2016, as colors in New York, California, Florida, and Texas turns significantly darker. In New York and California, individual contribution is more than doubled from 2016 to 2020.

__ __

# Question 5 - Contribution Comparison for Trump, Biden, Clinton in year 2020 and 2016

## 1. Total amount by individual and by Committee
### a. In Year 2020

In [34]:
%%sql
select cl.cmte_id, c.cand_name, cy.year, trans_from_auth, ttl_indiv_contrib,
    sum(trans_from_auth + ttl_indiv_contrib) total_contrib_received
from all_candidate
JOIN CMTE_LINK AS cl
ON cl.cmte_link_key = all_candidate.cmte_link_key
JOIN Candidate_Info AS c
ON c.info_key = all_candidate.info_key
JOIN Coverage_Year AS cy
ON cy.coverage_year_key = all_candidate.coverage_year_key
where cy.year = 2020 and c.cand_name like '%TRUMP, DONALD J.%' or cy.year = 2020 and c.cand_name = 'BIDEN, JOSEPH R JR'
group by cl.cmte_id, cy.year, c.cand_name, trans_from_auth, ttl_indiv_contrib
;

 * postgresql://student@/final_project_yu
2 rows affected.


[('C00580100', 'TRUMP, DONALD J.', 2020, Decimal('214226159.34'), Decimal('316611498.84'), Decimal('530837658.18')),
 ('C00703975', 'BIDEN, JOSEPH R JR', 2020, Decimal('229500000.00'), Decimal('719798548.33'), Decimal('949298548.33'))]

__2020 TRUMP VS BIDEN__

__TRUMP:__
+ amount of contributions from committees  ~215 millions
+ amount of contributions from individuals  ~315 millions
+ amount of total contributions from committees and individuals  ~530 millions

__BIDEN:__
+ amount of contributions from committees  ~230 millions
+ amount of contributions from individuals  ~720 millions
+ amount of total contributions from committees and individuals  ~950 millions

In [35]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2020biden%26trump.png")

### b. In Year 2016

In [35]:
%%sql
select cl.cmte_id, c.cand_name, cy.year, trans_from_auth, ttl_indiv_contrib,
    sum(trans_from_auth + ttl_indiv_contrib) total_contrib_received
from all_candidate
JOIN CMTE_LINK AS cl
ON cl.cmte_link_key = all_candidate.cmte_link_key
JOIN Candidate_Info AS c
ON c.info_key = all_candidate.info_key
JOIN Coverage_Year AS cy
ON cy.coverage_year_key = all_candidate.coverage_year_key
where cy.year = 2016 and c.cand_name like '%TRUMP%' or cy.year = 2016 and c.cand_name like 'CLINTON, HILLARY RODHAM / TIMOTHY MICHAEL KAINE'
group by cl.cmte_id, cy.year, c.cand_name, trans_from_auth, ttl_indiv_contrib
;

 * postgresql://student@/final_project_yu
2 rows affected.


[('C00577395', 'CLINTON, HILLARY RODHAM / TIMOTHY MICHAEL KAINE', 2016, Decimal('160760000.00'), Decimal('405664230.47'), Decimal('566424230.47')),
 ('C00580100', 'TRUMP, DONALD J.', 2016, Decimal('134598597.72'), Decimal('133622961.93'), Decimal('268221559.65'))]

__2016 CLINTON VS TRUMP__

__CLINTON:__
+ amount of contributions from committees  ~160 millions
+ amount of contributions from individuals  ~405 millions
+ amount of total contributions from committees and individuals  ~566 millions

__TRUMP:__
+ amount of contributions from committees  ~135 millions
+ amount of contributions from individuals  ~134 millions
+ amount of total contributions from committees and individuals  ~268 millions

In [36]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2016clinton%26trump.png")

### c. Trump in Year 2020 vs in Year 2016

In [36]:
%%sql
select cl.cmte_id, c.cand_name, cy.year, trans_from_auth, ttl_indiv_contrib,
    sum(trans_from_auth + ttl_indiv_contrib) total_contrib_received
from all_candidate
JOIN CMTE_LINK AS cl
ON cl.cmte_link_key = all_candidate.cmte_link_key
JOIN Candidate_Info AS c
ON c.info_key = all_candidate.info_key
JOIN Coverage_Year AS cy
ON cy.coverage_year_key = all_candidate.coverage_year_key
where c.cand_name like '%TRUMP, DONALD J.%'
group by cl.cmte_id, cy.year, c.cand_name, trans_from_auth, ttl_indiv_contrib;

 * postgresql://student@/final_project_yu
2 rows affected.


[('C00580100', 'TRUMP, DONALD J.', 2016, Decimal('134598597.72'), Decimal('133622961.93'), Decimal('268221559.65')),
 ('C00580100', 'TRUMP, DONALD J.', 2020, Decimal('214226159.34'), Decimal('316611498.84'), Decimal('530837658.18'))]

__2020 VS 2016 TRUMP__

__2016:__
+ amount of contributions from committees  ~135 millions
+ amount of contributions from individuals  ~134 millions
+ amount of total contributions from committees and individuals  ~268 millions

__2020:__ 
+ amount of contributions from committees  ~215 millions
+ amount of contributions from individuals  ~315 millions
+ amount of total contributions from committees and individuals  ~530 millions

In [37]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2016%262020trump.png")

## 2. Contribution by individual break down by month

__2020 Trump contribution from individual break down by month__

In [38]:
%%sql
select d.month, sum(transaction_amt)  from contribution_fact
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2020 and b.cmte_id = 'C00580100' and t.contribution_type = 'IND_COM'
group by d.month
order by d.month
;

 * postgresql://student@/final_project_yu
10 rows affected.


[(1, Decimal('2509156.00')),
 (2, Decimal('1970497.00')),
 (3, Decimal('1403127.00')),
 (4, Decimal('2377366.00')),
 (5, Decimal('3596392.00')),
 (6, Decimal('10103820.00')),
 (7, Decimal('11404479.00')),
 (8, Decimal('20097930.00')),
 (9, Decimal('35006601.00')),
 (10, Decimal('45995968.00'))]

__2016 Trump contribution by individual break down by month__

In [39]:
%%sql
select d.month, sum(transaction_amt)  from contribution_fact
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2016 and b.cmte_id = 'C00580100' and t.contribution_type = 'IND_COM'
group by d.month
order by d.month
;

 * postgresql://student@/final_project_yu
10 rows affected.


[(1, Decimal('268418.00')),
 (2, Decimal('487818.00')),
 (3, Decimal('721847.00')),
 (4, Decimal('477240.00')),
 (5, Decimal('1176479.00')),
 (6, Decimal('9883291.00')),
 (7, Decimal('11239106.00')),
 (8, Decimal('8289708.00')),
 (9, Decimal('7937314.00')),
 (10, Decimal('26497069.00'))]

__2020 Biden contribution by individual break down by month__

In [40]:
%%sql
select d.month, sum(transaction_amt)  from contribution_fact
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2020 and b.cmte_id = 'C00703975' and t.contribution_type = 'IND_COM'
group by d.month
order by d.month
;

 * postgresql://student@/final_project_yu
10 rows affected.


[(1, Decimal('6047480.00')),
 (2, Decimal('10205604.00')),
 (3, Decimal('27690175.00')),
 (4, Decimal('28311014.00')),
 (5, Decimal('20053588.00')),
 (6, Decimal('31495707.00')),
 (7, Decimal('28841450.00')),
 (8, Decimal('95885197.00')),
 (9, Decimal('111329285.00')),
 (10, Decimal('33598368.00'))]

__2020 Clinton contribution by individual break down by month__

In [43]:
%%sql
select d.month, sum(transaction_amt)  from contribution_fact
join beneficiary as b
on b.BENEFICIARY_KEY = contribution_fact.BENEFICIARY_KEY
join date as d
on d.date_key = contribution_fact.date_key
join TYPE as t
on t.type_key = contribution_fact.type_key
where d.year = 2016 and b.cmte_id = 'C00575795' and t.contribution_type = 'IND_COM'
group by d.month
order by d.month
;

 * postgresql://student@/final_project_yu
10 rows affected.


[(1, Decimal('9254485.00')),
 (2, Decimal('13283195.00')),
 (3, Decimal('12567343.00')),
 (4, Decimal('15046232.00')),
 (5, Decimal('15196836.00')),
 (6, Decimal('18082853.00')),
 (7, Decimal('20204335.00')),
 (8, Decimal('18887028.00')),
 (9, Decimal('29333655.00')),
 (10, Decimal('27800442.00'))]

In [39]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/monthly_sum_indiv.png")

__ __

## Question 6: Occupation breakdown for individual contributor supporting Democrat and Republican

## 1. 2016 Democratic

In [57]:
%%sql
select sum(transaction_amt) as sum_amt, o.occupation from contribution_fact
join TYPE as t
on t.type_key = contribution_fact.type_key
join date as d
on d.date_key = contribution_fact.date_key
join beneficiary as b
on b.beneficiary_key = contribution_fact.beneficiary_key
join contributor_occupation as o
on o.contributor_occupation_key = contribution_fact.contributor_occupation_key
where d.year = 2016 and d.month <= 10
and t.contribution_type = 'IND_COM' and b.cmte_pty_affiliation = 'DEM'
group by o.occupation
order by sum_amt desc
limit 10;

 * postgresql://student@/final_project_yu
10 rows affected.


[(Decimal('105026806.00'), 'RETIRED'),
 (Decimal('55073595.00'), 'ATTORNEY'),
 (Decimal('44199107.00'), 'NOT EMPLOYED'),
 (Decimal('20365689.00'), 'OWNER'),
 (Decimal('14448893.00'), 'HOMEMAKER'),
 (Decimal('14173240.00'), 'PHYSICIAN'),
 (Decimal('13746514.00'), 'PRESIDENT'),
 (Decimal('13667554.00'), 'CEO'),
 (Decimal('11598604.00'), 'CONSULTANT'),
 (Decimal('10620561.00'), 'PROFESSOR')]

In [1]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2016dem.png")

__As we can see from the data, retired people were the most contributors for the 2016 democratic campaign. I was surprised by that because, retired people do not have a great deal of income, but they ended of contributing a lot. Another surprising aspect is the fact that being that are not employed find themselves in the top 3 contributors for democrats.__

## 2. 2016 Republican

In [58]:
%%sql
select sum(transaction_amt) as sum_amt, o.occupation from contribution_fact
join TYPE as t
on t.type_key = contribution_fact.type_key
join date as d
on d.date_key = contribution_fact.date_key
join beneficiary as b
on b.beneficiary_key = contribution_fact.beneficiary_key
join contributor_occupation as o
on o.contributor_occupation_key = contribution_fact.contributor_occupation_key
where d.year = 2016 and d.month <= 10
and t.contribution_type = 'IND_COM' and b.cmte_pty_affiliation = 'REP'
group by o.occupation
order by sum_amt desc
limit 10;

 * postgresql://student@/final_project_yu
10 rows affected.


[(Decimal('89438556.00'), 'RETIRED'),
 (Decimal('24630535.00'), 'HOMEMAKER'),
 (Decimal('20503456.00'), 'PRESIDENT'),
 (Decimal('19470571.00'), 'PRESIDENT/CEO'),
 (Decimal('17262224.00'), 'CEO'),
 (Decimal('14834417.00'), 'EXECUTIVE'),
 (Decimal('14588343.00'), 'OWNER'),
 (Decimal('13241428.00'), 'ATTORNEY'),
 (Decimal('8296796.00'), 'PHYSICIAN'),
 (Decimal('7927145.00'), 'CHAIRMAN')]

In [2]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2016rep.png")

__Retired people also contributed the most for the republican campaign. It is safe to say retired people are most likely to contribute during the 2016 election. We see a lot of Executive/CEO people contributing for the 2016 Republican campaign. One can assume that, President Trumps connection with the corporate world might have an influence on that fact.__

## 3. 2020 Democrat

In [59]:
%%sql
select sum(transaction_amt) as sum_amt, o.occupation from contribution_fact
join TYPE as t
on t.type_key = contribution_fact.type_key
join date as d
on d.date_key = contribution_fact.date_key
join beneficiary as b
on b.beneficiary_key = contribution_fact.beneficiary_key
join contributor_occupation as o
on o.contributor_occupation_key = contribution_fact.contributor_occupation_key
where d.year = 2020 and d.month <= 10
and t.contribution_type = 'IND_COM' and b.cmte_pty_affiliation = 'DEM'
group by o.occupation
order by sum_amt desc
limit 10;

 * postgresql://student@/final_project_yu
10 rows affected.


[(Decimal('891977943.00'), 'FOUNDER'),
 (Decimal('284874386.00'), 'NOT EMPLOYED'),
 (Decimal('131012555.00'), 'RETIRED'),
 (Decimal('116098356.00'), 'PRESIDENTIAL CANDIDATE'),
 (Decimal('72043321.00'), 'ATTORNEY'),
 (Decimal('29162595.00'), 'PHYSICIAN'),
 (Decimal('20490733.00'), 'PROFESSOR'),
 (Decimal('19972381.00'), 'CONSULTANT'),
 (Decimal('16597819.00'), 'CEO'),
 (Decimal('15343864.00'), 'EXECUTIVE')]

In [5]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2020dem_2.png")

__For the 2020 democratic campaign we see that the people with a ‘founder’ occupation had the most contribution. The element of surprise here is again the amount of money collected from the people that are not employed. At number four, we see the presidential candidate which is President Biden with a lot of contribution to the democratic campaign.__

## 4. 2020 Republican

In [60]:
%%sql
select sum(transaction_amt) as sum_amt, o.occupation from contribution_fact
join TYPE as t
on t.type_key = contribution_fact.type_key
join date as d
on d.date_key = contribution_fact.date_key
join beneficiary as b
on b.beneficiary_key = contribution_fact.beneficiary_key
join contributor_occupation as o
on o.contributor_occupation_key = contribution_fact.contributor_occupation_key
where d.year = 2020 and d.month <= 10
and t.contribution_type = 'IND_COM' and b.cmte_pty_affiliation = 'REP'
group by o.occupation
order by sum_amt desc
limit 10;

 * postgresql://student@/final_project_yu
10 rows affected.


[(Decimal('263979594.00'), 'RETIRED'),
 (Decimal('21584505.00'), 'CEO'),
 (Decimal('20810922.00'), 'HOMEMAKER'),
 (Decimal('18929893.00'), 'OWNER'),
 (Decimal('18632051.00'), 'PRESIDENT'),
 (Decimal('13711933.00'), 'EXECUTIVE'),
 (Decimal('12890303.00'), 'ATTORNEY'),
 (Decimal('11308463.00'), 'PHYSICIAN'),
 (Decimal('9607518.00'), 'SELF-EMPLOYED'),
 (Decimal('7696477.00'), 'CHAIRMAN')]

In [4]:
from IPython.display import Image
Image(url="https://raw.githubusercontent.com/rainieluo2016/ISTM_6212/main/2020rep.png")

__In this table, there wasn’t much of a surprise. Most of the occupation listed here make well enough money and would not surprise us when they are top10__

### Conclusion:
__Out of the top 10 contributors based on occupation, in 2016 Republicans contributed a little over 100 million compared to the Democrats. But in the 2020 election year the democrats contributed a whooping 1,597,573,953 compared to only 399,151,659 contributed by Republicans. Money plays a big factor during an election campaign and the party that contributed more won on each of these election years. During the 2016 election, Republicans contributed more which resulted in President Trump being elected. In 2020, Democrats contributed more which resulted in President Biden being elected.__